### ISSUE TITLE
Mistake in Documentation

### ISSUE THREAD

**Issue by evan-gaertner** [OpenFAST/openfast#149] opened 2018-07-09 19:35 UTC
In the compiling instructions for Linux/Max, there is a mistake in the example cmake options for compiling with single precision.  It should be:

cmake -DDOUBLE_PRECISION:BOOL=OFF ..

Thanks,
Evan

**Comment by rafmudaf** [comment] 2018-07-09 20:50
Thank you for raising this issue @evan-gaertner. If you've fixed this on your end, feel free to issue a pull request with the updated documentation. Guidelines for doing this are available in the [openfast git section](http://openfast.readthedocs.io/en/master/source/dev/github_workflow.html#openfast-specific-git-flow). Note that you do not need to include regression test results in this case since it is strictly a documentation update.

**Comment by rafmudaf** [comment] 2018-07-12 23:19
This is fixed by #150

**Closed by rafmudaf** 2018-07-12 23:19 UTC
Labels: documentation
