### ISSUE TITLE
 Cannot find TurbSim full-field wind input

### ISSUE THREAD

**Issue by LeoHongLiZuo** [OpenFAST/openfast#1206] opened 2022-07-31 02:43 UTC
Hello guys,
I was using OpenFAST 3.0.0 and now I when I running 5MW_OC4Semi_WSt_WavesWN with turbusim meeting a problem.  
<img width="744" alt="eb6127e35aa8771bcdf4457954aa922" src="https://user-images.githubusercontent.com/108517989/182007264-4a97a25f-b0de-47c5-a2ec-8499340a09b1.png">
<img width="619" alt="e8d313d764f40eb6b1fcddd7995b6cf" src="https://user-images.githubusercontent.com/108517989/18200
<img width="619" alt="e8d313d764f40eb6b1fcddd7995b6cf" src="https://user-images.githubusercontent.com/108517989/182007570-ac2aeebf-d521-42dc-a42d-9defc24477f1.png">
<img width="681" alt="396760e2cbbe438311b5a6aab99dc93" src="https://user-images.githubusercontent.com/108517989/182007623-d0034f6c-a9fa-463e-b9d1-6d232d41eace.png">
as above,I take TurbSim produce file put in Wind file,but still show error.
So I would like to ask how to solve this pronlem. Thanks.

**Comment by jjonkman** [comment] 2022-08-01 12:56
Dear @LeoHongLiZuo,

It looks like you have not specified the path to the directory where the TurbSim wind data file is written.  InflowWind input file parameter `FileName_BTS` should be _"..\5MW_Baseline\Wind\90_12mps_twr.bts"_ to locate your wind file relative to your OpenFAST input file.

Best regards,

**Comment by jjonkman** [comment] 2022-11-17 19:14
I don't see any attachment...

**Comment by LeoHongLiZuo** [comment] 2022-11-18 12:40
Dear Jonkman,


I am very glad to receive your reply.


As shown in the picture below, the PDF I added in the email sent to you yesterday is my problem.





But I'm so sorry and I don't know why you haven't received it.I wonder if it got lost in transit.





This time in addition to still put the PDF in the attachment.I also added the question to in the body of the E-mail.



But I'm showing here that the clarity in the text is not very high,maybe you need to read PDF after all.



I'm really sorry to trouble you.



If you still haven't received it this time, I will present it to you in the form of pictures in the email tomorrow.




I'm glad you took time out of your busy schedule to reply me!



Looking forward to hearing from you again!


Yours,

Leo
   Dear Jonkman,

 The following is my question.

 10-MW OO-Star semisubmersible platform is used as the reference structure.

 I want to observe whether the platform will stabilize within a certain range when there

 is no wind��no waves and no initial displacement is set.

 So I made the following Settings.Like Figure.1.

 Figure.1 parameter setting

 But the weird thing is, after run the Openfast and get the data��draw a time curve for

 the data,the degree of platform freedom varies greatly.Especially in Surge and Heave,

 like Figure.2(a)��Figure.2(b).

 Figure.2(a) Surge time duration

 Figure.2(b) Heave time duration

 
 



   So I was wondering if because of open Aero module �� Servo module or Mooring

 module. As I turn off modules one by one , but I didn't get the results I wanted.

 After that I shut down all the modules except the Elast module, like Figure.3.

 Figure.3 parameter setting

 But what drives me crazy is the next degree of freedom time duration, like Figure.4

 Figure.4(a) Surge time duration

 Figure.4(b) Heave time duration

 
 



   Figure.4(c) Pitch time duration

 In my opinion, when there is no wind��no waves and no initial displacement is set��and

 without any external force, the platform should have no movement after stabilization,

 or the movement should be in a very small range.

 But when I set it up there is no wind��no waves and no initial displacement is set��the

 platform has a greater degree of movement.

 After that I shut down all the modules except the Elast module, also don't have an

 ideal time curve.

 I don't know what I did wrong. I really want to ask you this question

 Thanks a lot again!

 
 



   
 











------------------ 原始邮件 ------------------
发件人:                                                                                                                        "OpenFAST/openfast"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月18日(星期五) 凌晨3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFAST/openfast]  Cannot find TurbSim full-field wind input (Issue #1206)





 
I don't see any attachment...

**Comment by jjonkman** [comment] 2022-11-18 14:54
Dear @LeoHongLiZuo,

I have not received your e-mail (perhaps it was blocked by NREL's firewall, depending on what you attached) and don't see the Figures in your post.

Best regards,

**Comment by LeoHongLiZuo** [comment] 2022-11-19 14:22
Dear Jonkman,


I am very glad to hear from you again.



But I'm sorry you didn't receive my question again.



Next I will write my question in the email，but because of the lack of pictures I think there may be a lack of clarity.

The following is my question.

10-MW OO-Star semisubmersible platform is used as the reference structure.

I want to observe whether the platform will stabilize within a certain range when there is no wind、no waves and no initial displacement is set.

But the weird thing is, after run the Openfast and get the data，draw a time curve for the data,the degree of platform freedom varies greatly.

So I was wondering if because of open Aero module、Servo module or Mooring module. 


As I shut down all the modules except the Elast module one by one , but I didn't get the results I wanted.



In my opinion, when there is no wind、no waves and no initial displacement is set，and without any external force, the platform should have no movement after stabilization, or the movement should be in a very small range.


But when I set it up&nbsp;there is no wind、no waves and no initial displacement is set，the platform has a greater degree of movement.

After that I shut down all the modules except the Elast module, also don't have an ideal time curve.

I don't know what I did wrong. I really want to ask you this question.






Finally, could you please send me your personal email address, this will prevent the same problems from occurring when I ask you questions in the future.

Although I know it's very presumptuous of me to ask.

Thank you again for taking time out of your busy schedule to read and reply to my letter.

Looking forward to hearing from you again.

Yours,

Leo
















------------------ 原始邮件 ------------------
发件人:                                                                                                                        "OpenFAST/openfast"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月18日(星期五) 晚上10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFAST/openfast]  Cannot find TurbSim full-field wind input (Issue #1206)





 
Dear @LeoHongLiZuo,
 
I have not received your e-mail (perhaps it was blocked by NREL's firewall, depending on what you attached) and don't see the Figures in your post.
 
Best regards,

**Comment by jjonkman** [comment] 2022-11-26 13:16
Dear @LeoHongLiZuo,

You haven't provided enough information to guess what the problem is.  You should be able to upload data files or images in your post or share a link to a Google drive or the like with more information.

Best regards,

**Comment by LeoHongLiZuo** [comment] 2023-04-06 13:58
Dear Jonkman，
I have a new question about Openfast. 

I want set CURRENT with CurrMod (2: user-defined from routine UserCurrent) in HydroDyn.
But I'm not find it File input path and not clear how to set user-defined.
And I'm also not find solution on Openfast Developer Documentation.
Looking forward to hearing from you! 			
Thanks a lot! 

Yours, 
Leo




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "OpenFAST/openfast"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月26日(星期六) 晚上9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFAST/openfast]  Cannot find TurbSim full-field wind input (Issue #1206)





 
Dear @LeoHongLiZuo,
 
You haven't provided enough information to guess what the problem is.  You should be able to upload data files or images in your post or share a link to a Google drive or the like with more information.
 
Best regards,

**Comment by jjonkman** [comment] 2023-04-06 14:15
Dear @LeoHongLiZuo,

Selecting `CurrMod` = 2 in HydroDyn will tell HydroDyn to call user-written `SUBROUTINE UserCurrent()` to return the wave current velocities as a function of depth.  There is a template of `SUBROUTINE UserCurrent()` in HydroDyn source file _Current.f90_.  You'll have to modify the `UserCurrent()` source code and recompile OpenFAST to use this functionality.

Best regards,

**Comment by LeoHongLiZuo** [comment] 2023-04-07 01:54
Dear Jonkman，I have found the location you descrubed.But I'm not familiar with how to complie...
I wonder if you have any examples for reference. I want to learn about it...
Or is there any reference on the Github/Openfast.

Looking forward to hearing from you again! 			
Thanks a lot! 

Yours, 
Leo


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "OpenFAST/openfast"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月6日(星期四) 晚上10:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFAST/openfast]  Cannot find TurbSim full-field wind input (Issue #1206)





 
Dear @LeoHongLiZuo,
 
Selecting CurrMod = 2 in HydroDyn will tell HydroDyn to call user-written SUBROUTINE UserCurrent() to return the wave current velocities as a function of depth.  There is a template of SUBROUTINE UserCurrent() in HydroDyn source file Current.f90.  You'll have to modify the UserCurrent() source code and recompile OpenFAST to use this functionality.
 
Best regards,

**Comment by jjonkman** [comment] 2023-04-07 21:16
Dear @LeoHongLiZuo,

It looks like you asked the same question in a separate post, which I've now answered there: https://github.com/OpenFAST/openfast/discussions/1517.

I'll now close this issue.

**Closed by jjonkman** 2023-04-07 21:17 UTC
Labels: Type: Question, Module: HydroDyn, Module: InflowWind, Module: TurbSim
