### ISSUE TITLE
@jjonkman  suggested me to compile using OpenFAST libraries. I am able to compile without any errors. Thanks

### ISSUE THREAD

**Issue by AngelCamargoUSP** [OpenFAST/openfast#624] opened 2021-01-07 20:14 UTC
@jjonkman  suggested me to compile using OpenFAST libraries. I am able to compile without any errors. Thanks

_Originally posted by @abhinaygoga in https://github.com/OpenFAST/openfast/issues/152#issuecomment-697143140_

Hello @abhinaygoga

Please, could you tell me what do you mean with OpenFAST Libraries? I think I'm having the same problem.

**Comment by andrew-platt** [comment] 2021-01-13 16:27
duplicate of #625 ?

Closing

**Closed by andrew-platt** 2021-01-13 16:27 UTC

**Comment by abhinaygoga** [comment] 2021-01-13 17:58
Hey Andy,

I am replying from my phone. If I remember correctly, I think the thread
you are talking about is to compile standalone BeamDyn driver!?

Whatever it is, FAST and OpenFAST have connecting libraries. You can find a
folder named FAST libraries in the downloaded FAST library (folder). If it
is for standalone BeamDyn compilation, you can just take the BeamDyn
libraries ,fortran code and relevant files from OpenFAST and copy it in
your BeamDyn compilation folder. Then try to compile.

Hope this helps. Cheers

Regards
Abhinay Goga
