### ISSUE TITLE
OpenFast Compilation Error

### ISSUE THREAD

**Issue by Jochen-IST** [OpenFAST/openfast#87] opened 2018-01-30 10:15 UTC
Dear developers, 

I am new with the OpenFast project and tried to compile OpenFast on a 64-bit LINUX machine (CentOS 6.9) and a GNU 4.4.7 C and Fortran compiler.
I could create the Makefiles (cmake) for OpenFAST. Here are the messages of "cmake": 

-- The CXX compiler identification is GNU 4.4.7
-- The C compiler identification is GNU 4.4.7
-- The Fortran compiler identification is GNU 4.4.7
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- A library with BLAS API found.
-- A library with BLAS API found.
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
-- Setting system file as: src/SysGnuLinux.f90
-- Configuring done
-- Generating done
-- Build files have been written to: /fs/jochen/OpenFAST/build

But when running "make", I get the following error messages for the compilation of SysGnuLinux.f90:

build-g44:/fs/jochen/OpenFAST/build>make
[  4%] Built target fast_registry
[  5%] Building Fortran object
modules-local/nwtc-library/CMakeFiles/nwtclibs.dir/src/SysGnuLinux.f90.o
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:181.12:

   REAL(DbKi), INTENT(IN)       :: DblNum
            1
Error: Kind -1 not supported for type REAL at (1)
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:227.15:

      REAL(QuKi), INTENT(IN)     :: x             ! input 
               1
Error: Kind -1 not supported for type REAL at (1)
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:228.15:

      REAL(QuKi)                 :: NWTC_ERFR16   ! result
               1
Error: Kind -1 not supported for type REAL at (1)
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:222.3:

   FUNCTION NWTC_ERFR16( x )
   1
Error: Function result 'nwtc_erfr16' at (1) has no IMPLICIT type
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:266.15:

      REAL(QuKi), INTENT(IN)     :: x             ! input 
               1
Error: Kind -1 not supported for type REAL at (1)
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:267.15:

      REAL(QuKi)                 :: NWTC_GammaR16  ! result
               1
Error: Kind -1 not supported for type REAL at (1)
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:261.3:

   FUNCTION NWTC_GammaR16( x )
   1
Error: Function result 'nwtc_gammar16' at (1) has no IMPLICIT type
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:375.15:

      REAL(DbKi), INTENT(inout)           :: Inf_D          ! IEEE value for
Na
               1
Error: Kind -1 not supported for type REAL at (1)
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:376.15:

      REAL(DbKi), INTENT(inout)           :: NaN_D          ! IEEE value for
In
               1
Error: Kind -1 not supported for type REAL at (1)
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:382.15:

      REAL(DbKi)                          :: Neg_D          ! a negative
real(D
               1
Error: Kind -1 not supported for type REAL at (1)
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:391.23:

      Neg_D = -1.0_DbKi
                       1
Error: Missing kind-parameter at (1)
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:398.22:

      Neg_D = 0.0_DbKi
                      1
Error: Missing kind-parameter at (1)
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:401.22:

      Inf_D = 1.0_DbKi / Neg_D
                      1
Error: Missing kind-parameter at (1)
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:169.26:

   FUNCTION Is_NaN( DblNum )
                          1
Error: Symbol 'dblnum' at (1) has no IMPLICIT type
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:222.26:

   FUNCTION NWTC_ERFR16( x )
                          1
Error: Symbol 'x' at (1) has no IMPLICIT type
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:261.28:

   FUNCTION NWTC_GammaR16( x )
                            1
Error: Symbol 'x' at (1) has no IMPLICIT type
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:365.39:

   SUBROUTINE Set_IEEE_Constants( NaN_D, Inf_D, NaN, Inf )   
                                       1
Error: Symbol 'nan_d' at (1) has no IMPLICIT type
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:365.46:

   SUBROUTINE Set_IEEE_Constants( NaN_D, Inf_D, NaN, Inf )   
                                              1
Error: Symbol 'inf_d' at (1) has no IMPLICIT type
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:394.26:

      NaN_D = SQRT ( Neg_D )
                          1
Error: Symbol 'neg_d' at (1) has no IMPLICIT type
make[3]: ***
[modules-local/nwtc-library/CMakeFiles/nwtclibs.dir/src/SysGnuLinux.f90.o]
Error 1
make[2]: ***
[modules-local/nwtc-library/CMakeFiles/nwtclibs.dir/src/SysGnuLinux.f90.o.pr
ovides] Error 2
make[1]: *** [modules-local/nwtc-library/CMakeFiles/nwtclibs.dir/all] Error
2
make: *** [all] Error 2

Maybe someone has an idea what's going wrong.
Thanks in advance for your help!
Jochen Lang

**Comment by sayerhs** [comment] 2018-02-02 14:50
It appears that the GCC-4.4.7 `gfortran` version in your system does not seem to be able to support the REAL KINDs defined in [SingPrec.f90](https://github.com/OpenFAST/openfast/blob/master/modules-local/nwtc-library/src/SingPrec.f90#L42). A quick workaround would be to replace the three lines with the following 

```
INTEGER, PARAMETER              :: QuKi     = 16    !< Kind for 16-byte, floating-point numbers
INTEGER, PARAMETER              :: R8Ki     = 8     !< Kind for eight-byte floating-point numbers
INTEGER, PARAMETER              :: SiKi     = 4     !< Kind for four-byte, floating-point numbers
```

I suspect you might still have issues with `QuKi` not being supported at this stage. Can you try the above and let us know? 

We might have to add some CMake rules to check for supported REAL KINDs when building on Linux systems.

**Comment by Jochen-IST** [comment] 2018-02-05 09:06
The above suggestion did not work:

```
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:181.12:

   REAL(DbKi), INTENT(IN)       :: DblNum
            1
Error: Kind 16 not supported for type REAL at (1)
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:227.15:

      REAL(QuKi), INTENT(IN)     :: x             ! input 
               1
Error: Kind 16 not supported for type REAL at (1)
/fs/jochen/OpenFAST/modules-local/nwtc-library/src/SysGnuLinux.f90:228.15:

      REAL(QuKi)                 :: NWTC_ERFR16   ! result
               1
Error: Kind 16 not supported for type REAL at (1)
```

But meanwhile, I could solve the problem:
I could switch to a CentOS 7.2.1511 system with gcc version 4.8.5.  Here, using the original SigPrec.f90,  the compilation process ran without errors and I could start the OpenFAST executable.
The next step wil be to compile the regression test and the unit test. I will inform you about the progress.

**Comment by bjonkman** [comment] 2018-02-05 19:04
FYI, there are some known compiling errors that were documented in the [Compiling Instructions for FAST8](https://github.com/old-NWTC/FAST/blob/master/Compiling/CompilingInstructions_FASTv8.docx):
1. The version of gfortran must be at least 4.6.0. NWTC Library uses some quad-precision variables, which are not supported in earlier versions of gfortran.  
    _Possible workarounds: You might be able to set QuKi to some other supported real kind that is not 4 or 8 (not sure REAL(2) is supported, but you could try); otherwise, you'd have to set QuKi to 4 or 8 and remove the QuKi MODULE PROCEDURE lines from all the INTERFACE blocks at the top of the NWTC Library source files._
2. Intel Fortran must be version 11 or later. NWTC Library uses the gamma() function, which is not provided in earlier versions. 
_Possible workarounds: You can write your own gamma() function in the SysI*.f90 files, or remove the calls to gamma() (e.g., set nwtc_gamma = 1) and avoid using IceDyn and the wave spreading features of HydroDyn._

I'd recommend that you put a minimum version requirement for both gfortran and ifort compilers in cmake.

**Comment by Jochen-IST** [comment] 2018-02-06 16:20
I could pass the Unit Test without problems.
But for the Regression Test, I got the following result (I didn't change any source code): 

```
65% tests passed, 11 tests failed out of 31

Label Time Summary:
aerodyn14    = 1053.53 sec*proc (7 tests)
aerodyn15    = 10333.96 sec*proc (19 tests)
beamdyn      = 832.16 sec*proc (5 tests)
dynamic      =  84.62 sec*proc (1 test)
elastodyn    = 10643.49 sec*proc (25 tests)
hydrodyn     = 8356.97 sec*proc (7 tests)
map          = 331.74 sec*proc (3 tests)
moordyn      = 297.73 sec*proc (1 test)
openfast     = 11387.49 sec*proc (26 tests)
servodyn     = 11385.46 sec*proc (25 tests)
static       =   3.54 sec*proc (3 tests)
subdyn       = 7727.49 sec*proc (3 tests)

Total Test time (real) = 11475.85 sec

The following tests FAILED:
	  9 - UAE_Dnwind_YRamp_WSt (Failed)
	 12 - WP_VSP_ECD (Failed)
	 17 - SWRT_YFree_VS_WTurb (Failed)
	 18 - 5MW_Land_DLL_WTurb (Failed)
	 19 - 5MW_OC3Mnpl_DLL_WTurb_WavesIrr (Failed)
	 20 - 5MW_OC3Trpd_DLL_WSt_WavesReg (Failed)
	 21 - 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth (Failed)
	 22 - 5MW_ITIBarge_DLL_WTurb_WavesIrr (Failed)
	 23 - 5MW_TLP_DLL_WTurb_WavesIrr_WavesMulti (Failed)
	 24 - 5MW_OC3Spar_DLL_WTurb_WavesIrr (Failed)
	 25 - 5MW_OC4Semi_WSt_WavesWN (Failed)

```
Taking for example Test 25, I got the following messages:

```
test 25
      Start 25: 5MW_OC4Semi_WSt_WavesWN

25: Test command: /bin/python3 "/fs/jochen/OpenFAST/reg_tests/executeOpenfastRegressionCase.py" "5MW_OC4Semi_WSt_WavesWN" "/fs/jochen/OpenFAST/build/glue-codes/fast/openfast" "/fs/jochen/OpenFAST/reg_tests/.." "/fs/jochen/OpenFAST/build/reg_tests/glue-codes/fast" "0.00001" "Linux" "GNU"
25: Test timeout computed to be: 5400
25: -- Using gold standard files with machine-compiler type macos-gnu
25: /fs/jochen/OpenFAST/build/glue-codes/fast/openfast /fs/jochen/OpenFAST/build/reg_tests/glue-codes/fast/5MW_OC4Semi_WSt_WavesWN/5MW_OC4Semi_WSt_WavesWN.fst > /fs/jochen/OpenFAST/build/reg_tests/glue-codes/fast/5MW_OC4Semi_WSt_WavesWN/5MW_OC4Semi_WSt_WavesWN.log
25: COMPLETE with code 0
25/31 Test #25: 5MW_OC4Semi_WSt_WavesWN ..................***Failed  297.73 sec

```
It seems that the test itself runs without errors but the comparison to the reference results fails.
Here is the HTML and the OUT file from the subdirectory OpenFAST\build\reg_tests\glue-codes\fast\5MW_OC4Semi_WSt_WavesWN: 
[5MW_OC4Semi_WSt_WavesWN.out.zip](https://github.com/OpenFAST/openfast/files/1699849/5MW_OC4Semi_WSt_WavesWN.out.zip)

Maybe someone can help?

**Comment by rafmudaf** [comment] 2018-02-06 18:22
@Jochen-IST Just to verify, these results are from a CentOS 7.2 machine with gcc 4.8? Also, which math library are you linking to openfast? And it looks like you're on the master branch, correct?

**Comment by Jochen-IST** [comment] 2018-02-07 07:56
Yes, CentOS Linux release 7.2.1511, gcc version 4.8.5, and I am on the master branch.
Concerning math library,here is my CMakeCache.txt of the build subdirectory. Does this help?
[CMakeCache.txt.zip](https://github.com/OpenFAST/openfast/files/1702164/CMakeCache.txt.zip)

**Comment by Jochen-IST** [comment] 2018-02-08 08:59
I just checked some result curves in the time domain in comparison of the reference results "linux-intel", "macos-gnu" and my result version, which I called "linux-gnu". I compared the result curves of the OUT files of the "failed" regression test "5MW_OC4Semi_WSt_WavesWN". The result curves are "RotSpeed", "GenSpeed", "BldPitch" and "ANCHTEN1" exemplarily. (s. attachment). It seems that even the reference results of "linux-intel" and "macos-gnu" differ significantly from each other and that my "linux-gnu" solution is a third possible solution. Is there such a strong numerical dependency of the OpenFAST results from the operation system and the compiler? And what does this mean for the physical interpretation of the simulation results? 
![anchten1](https://user-images.githubusercontent.com/35954192/35963826-4b2f845e-0cb6-11e8-8b49-26e7a00d31bc.JPG)
![bldpitch1](https://user-images.githubusercontent.com/35954192/35963827-4b523990-0cb6-11e8-9b16-abc11491b20f.JPG)
![genspeed](https://user-images.githubusercontent.com/35954192/35963828-4b6cbbe4-0cb6-11e8-882f-b6804d47459f.JPG)
![rotspeed](https://user-images.githubusercontent.com/35954192/35963829-4b8bdc90-0cb6-11e8-95cf-f1dc837a7ca4.JPG)

**Comment by jjonkman** [comment] 2018-02-15 22:50
@Jochen-IST -- These differences are caused by differences in the intrinsic pseudo-random number generator across different compilers and operating systems (yielding different wave kinematics time series within HyrdoDyn).  I just opened a separate Open issue ( #89) regarding this, which makes cross comparisons of time-domain solutions difficult.

**Comment by rafmudaf** [comment] 2018-05-30 21:06
This issue resulted in

- Adding minimum compiler versions to cmake per @bjonkman's suggestion
- Opening issue #89 

A distinct issue should be opened to discuss the solution differences between machine and compilers, if thats still a concern. Otherwise, I'm closing this issue as resolved.

**Closed by rafmudaf** 2018-05-30 21:06 UTC
Labels: build-issues, cmake, unix
