### ISSUE TITLE
OPENFAST error with Simulink

### ISSUE THREAD

**Issue by JaredSP031** [OpenFAST/openfast#2367] opened 2024-08-12 13:27 UTC
Hello, I'm new at working with OpenFast, I'm trying to run the Openloop file but I get this error.  I don't know where to get the correct input file. Could someone help me with that.

>> Run_OpenLoop

 **************************************************************************************************
 OpenFAST

 Copyright (C) 2024 National Renewable Energy Laboratory
 Copyright (C) 2024 Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v3.5.3
 Compile Info:
  - Compiler: Intel(R) Fortran Compiler 2021
  - Architecture: 64 bit
  - Precision: single
  - OpenMP: No
  - Date: Apr 11 2024
  - Time: 21:34:48
 Execution Info:
  - Date: 08/12/2024
  - Time: 15:26:23+0200

  OpenFAST completed.

Error using Run_OpenLoop (line 12)
Error reported by S-function 'FAST_SFunc' in 'OpenLoop/FAST Nonlinear Wind Turbine/S-Function':
FAST_InitializeAll:FAST_Init:FAST_ReadPrimaryFile:OpenFInpFile:The input file, "

**Comment by deslaughter** [comment] 2024-08-12 13:40
The location of the input file is specified in `Run_OpenLoop.m` in the `FAST_InputFileName` variable. If this hasn't been modified, then it points to `../../../reg_tests/r-test/glue-codes/openfast/AOC_WSt/AOC_WSt.fst` which is for a file in the regression tests. Check to see if this file exists. If the `r-test` directory is empty, then the `r-test` submodule probably hasn't been initialized. The regression test files are stored in a git submodule (separate repository) because these files are rather large and take a while to download. Please try initialializing the submodule by running `git submodule update --init --recursive` within the cloned OpenFAST repo.

**Comment by JaredSP031** [comment] 2024-08-12 14:01
![Captura de pantalla 2024-08-12 155448](https://github.com/user-attachments/assets/2a640ad9-f074-4f58-87e7-275261bbd353)
This is how I have it written, I've already tried changing names and paths but does not work. The r-test directory has al ready several files (Generated by fast, I guess).

**Comment by deslaughter** [comment] 2024-08-12 14:16
Please try removing the double quotes from around the file path, they're probably not necessary.

**Comment by JaredSP031** [comment] 2024-08-12 14:21
![image](https://github.com/user-attachments/assets/12ff0e8a-8ff1-4441-9f69-e8cbd0e6ce94)
Still the issue :(

**Comment by deslaughter** [comment] 2024-08-12 14:53
Try changing the backslashes to forward slashes. Or, since the input file is in the same directory as `Run_OpenLoop.m`, try setting the path to just `WTInputFile.fst`.

**Comment by deslaughter** [comment] 2024-08-19 14:43
@JaredSP031 Were you able to get this working? If so, could you please close this issue?

**Comment by JaredSP031** [comment] 2024-08-20 09:58
I solve the reading of the input file, but sttill have truble on the arrangement, it says that I have different size vectors.
Like this error:
    Error using Run_OpenLoop (line 12)
    Error in port widths or dimensions. 'Output Port 1' of 'OpenLoop/FAST Nonlinear Wind Turbine/Mux1' is a one dimensional vector
    with 51 elements.
    Error using Run_OpenLoop (line 12)
    Error in port widths or dimensions. 'Input Port 1' of 'OpenLoop/FAST Nonlinear Wind Turbine/S-Function' is a one dimensional
    vector with 8 elements.

**Closed** 2024-08-20 13:23 UTC
Labels: Type: Question, Sytem: MATLAB/Simulink
