### ISSUE TITLE
Error compiling in Visual Studio

### ISSUE THREAD

**Issue by sxs007** [OpenFAST/openfast#287] opened 2019-05-07 17:04 UTC
I get the followint error compling the version from Github:

1>------ Build started: Project: FAST_Registry, Configuration: Release x64 ------
1>  data.c
1>  gen_c_types.c
1>  gen_module_files.c
1>..\..\modules-local\openfast-registry\src\gen_module_files.c(2370): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>..\..\modules-local\openfast-registry\src\gen_module_files.c(2382): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>  misc.c
1>..\..\modules-local\openfast-registry\src\misc.c(418): warning C4013: 'getpid' undefined; assuming extern returning int
1>  my_strtok.c
1>  registry.c
1>..\..\modules-local\openfast-registry\src\registry.c(38): warning C4013: 'getpid' undefined; assuming extern returning int
1>  reg_parse.c
1>..\..\modules-local\openfast-registry\src\reg_parse.c(272): warning C4102: 'normal': unreferenced label
1>  sym.c
1>  symtab_gen.c
1>  type.c
1>..\..\modules-local\openfast-registry\src\type.c(187): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>  Generating code
1>  73 of 74 functions (98.6%) were compiled, the rest were copied from previous compilation.
1>    0 functions were new in current compilation
1>    0 functions had inline decision re-evaluated but remain unchanged
1>  Finished generating code
1>  FAST_Registry.vcxproj -> C:\Work\Vault\NREL\OpenFAST - Copy\vs-build\Registry\..\..\build\bin\Registry.exe
1>  FAST_Registry.vcxproj -> ..\..\build\bin\Registry.pdb (Full PDB)
2>------ Build started: Project: MAP_dll, Configuration: Release x64 ------
2>  Performing Custom Build Tools
2>  ======================================================================
2>
2>  ----- FAST Registry --------------
2>  ----------------------------------------------------------
2>  input file: ..\..\modules-ext\map\src\MAP_Registry.txt
2>  opening ..\..\modules-local\nwtc-library\src/Registry_NWTC_Library.txt
2>  generating ..\..\build\types-files/MAP_Types.f90
2>CUSTOMBUILD : Registry warning : derived data type Ver of type progdesc is not passed through C interface
2>CUSTOMBUILD : Registry warning : derived data type PtFairDisplacement of type meshtype is not passed through C interface
2>CUSTOMBUILD : Registry warning : derived data type ptFairleadLoad of type meshtype is not passed through C interface
2>
2>  Registry for MAP completed.
2>   
2>  ======================================================================
2>  bstraux.c
2>..\..\modules-ext\map\src\bstring\bstraux.c(1004): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
2>..\..\modules-ext\map\src\bstring\bstraux.c(1017): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
2>  bstrlib.c
2>..\..\modules-ext\map\src\bstring\bstrlib.c(367): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
2>  dpmpar.c
2>  enorm.c
2>  enorm_u.c
2>  lmder.c
2>  lmpar.c
2>  qrfac.c
2>  qrsolv.c
2>  freedata.c
2>  jacobian.c
2>  lineroutines.c
2>  mapapi.c
2>  maperror.c
2>  mapinit.c
2>  numeric.c
2>  outputstream.c
2>  residual.c
2>  simclist.c
2>  lmroutines.cc
2>     Creating library ..\..\build\bin\MAP_x64.lib and object ..\..\build\bin\MAP_x64.exp
2>  Generating code
2>  292 of 293 functions (99.7%) were compiled, the rest were copied from previous compilation.
2>    0 functions were new in current compilation
2>    0 functions had inline decision re-evaluated but remain unchanged
2>  Finished generating code
2>  MAP_dll.vcxproj -> C:\Work\Vault\NREL\OpenFAST - Copy\vs-build\MAPlib\..\..\build\bin\MAP_x64.dll
2>  MAP_dll.vcxproj -> ..\..\build\bin\MAP_x64.pdb (Full PDB)
C:\Work\Vault\NREL\OpenFAST - Copy\modules-local\nwtc-library\src\SysMatlab.f90 : warning: Module 'x64\Release\syssubs.mod' is created by both 'C:\Work\Vault\NREL\OpenFAST - Copy\modules-local\nwtc-library\src\SysMatlab.f90' and 'C:\Work\Vault\NREL\OpenFAST - Copy\modules-local\nwtc-library\src\SysIVF.f90'.
3>------ Build started: Project: FASTlib, Configuration: Release x64 ------
3>Performing Pre-Build Event...
3>Compiling with Intel(R) Visual Fortran Compiler 17.0.2.187 [Intel(R) 64]...
3>Map_Types.f90
3>ifort: command line warning #10161: unrecognized source type 'Copy\vs-build\FASTlib\\..\gitVersionInfo.h''; object file assumed
3>ifort: error #10273: Fatal error in C:\PROGRA~2\INTELS~1\COMPIL~1\windows\bin\intel64\fortcom, terminated by 0xc0000005
3>map.f90
3>ifort: command line warning #10161: unrecognized source type 'Copy\vs-build\FASTlib\\..\gitVersionInfo.h''; object file assumed
3>ifort: error #10273: Fatal error in C:\PROGRA~2\INTELS~1\COMPIL~1\windows\bin\intel64\fortcom, terminated by 0xc0000005
3>FAST_Types.f90
3>ifort: command line warning #10161: unrecognized source type 'Copy\vs-build\FASTlib\\..\gitVersionInfo.h''; object file assumed
3>ifort: error #10273: Fatal error in C:\PROGRA~2\INTELS~1\COMPIL~1\windows\bin\intel64\fortcom, terminated by 0xc0000005
3>FAST_Mods.f90
3>ifort: command line warning #10161: unrecognized source type 'Copy\vs-build\FASTlib\\..\gitVersionInfo.h''; object file assumed
3>ifort: error #10273: Fatal error in C:\PROGRA~2\INTELS~1\COMPIL~1\windows\bin\intel64\fortcom, terminated by 0xc0000005
3>OpenFOAM.f90
3>ifort: command line warning #10161: unrecognized source type 'Copy\vs-build\FASTlib\\..\gitVersionInfo.h''; object file assumed
3>ifort: error #10273: Fatal error in C:\PROGRA~2\INTELS~1\COMPIL~1\windows\bin\intel64\fortcom, terminated by 0xc0000005
3>SuperController.f90
3>ifort: command line warning #10161: unrecognized source type 'Copy\vs-build\FASTlib\\..\gitVersionInfo.h''; object file assumed
3>ifort: error #10273: Fatal error in C:\PROGRA~2\INTELS~1\COMPIL~1\windows\bin\intel64\fortcom, terminated by 0xc0000005
3>FAST_Solver.f90
3>ifort: command line warning #10161: unrecognized source type 'Copy\vs-build\FASTlib\\..\gitVersionInfo.h''; object file assumed
3>ifort: error #10273: Fatal error in C:\PROGRA~2\INTELS~1\COMPIL~1\windows\bin\intel64\fortcom, terminated by 0xc0000005
3>FAST_Lin.f90
3>ifort: command line warning #10161: unrecognized source type 'Copy\vs-build\FASTlib\\..\gitVersionInfo.h''; object file assumed
3>ifort: error #10273: Fatal error in C:\PROGRA~2\INTELS~1\COMPIL~1\windows\bin\intel64\fortcom, terminated by 0xc0000005
3>FAST_Subs.f90
3>ifort: command line warning #10161: unrecognized source type 'Copy\vs-build\FASTlib\\..\gitVersionInfo.h''; object file assumed
3>ifort: error #10273: Fatal error in C:\PROGRA~2\INTELS~1\COMPIL~1\windows\bin\intel64\fortcom, terminated by 0xc0000005
3>
3>Build log written to  "file://C:\Work\Vault\NREL\OpenFAST%20-%20Copy\vs-build\FASTlib\x64\Release\BuildLog.htm"
3>FASTlib - 9 error(s), 9 warning(s)
========== Build: 2 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by bjonkman** [comment] 2019-05-07 19:22
I think the problem is that the build command isn't properly parsing the spaces in your path name. I think the GIT_INCLUDE_FILE preprocessor directive in the FASTlib project should include double quotes instead of single quotes to fix this problem.

**Comment by rafmudaf** [comment] 2019-07-01 22:06
closed by pr #288

**Closed by rafmudaf** 2019-07-01 22:06 UTC
Labels: Type: Bug
