### ISSUE TITLE
Bug report - Using FAST_SFunc (OpenFAST compiled on Visual Studio Pro 2013)

### ISSUE THREAD

**Issue by AngelCamargoUSP** [OpenFAST/openfast#632] opened 2021-01-14 16:18 UTC
**Bug description**
Hello again @andrew-platt @bjonkman @jjonkman 

I compiled OpenFAST recently using VS Pro 2013. All seem like it's ok about the compilation but now I got this error while trying to run the sample named "OpenLoop" for Simulink. I  recompiled OpenFAST and created the SFunc again and again. So I don't know if there is something wrong with the compiled file or I'm missing some file/action/configuration before running the sample. Please help me! 
PSD: I added the .MEXW64 and .dll files to the same directory which .fst file is.
Thank you very much! 

![Create_SFunc](https://user-images.githubusercontent.com/77124247/104616678-5a366080-5669-11eb-9e62-65009888fd75.jpg)
![image](https://user-images.githubusercontent.com/77124247/104617741-8f8f7e00-566a-11eb-8f2e-4c955bfa6aef.png)

**Comment by bjonkman** [comment] 2021-01-14 16:24
Is there anything printed on the line after the "error reported by S-function `FAST_SFunc` in OpenLoop" line? or is that blank?

**Comment by AngelCamargoUSP** [comment] 2021-01-14 17:13
> Is there anything printed on the line after the "error reported by S-function `FAST_SFunc` in OpenLoop" line? or is that blank?
Hello Bonnie. Thanks for answering.
It is blank.

**Comment by AngelCamargoUSP** [comment] 2021-01-18 21:04
Hello! Who could help me? I'm still having this error.

**Comment by bjonkman** [comment] 2021-01-18 22:05
It appears that OpenFAST is ending early for some reason. Because there are no messages about the error, it is difficult to determine what the cause is.  Does this run with a different OpenFAST input file? Does it generate any other files that might give some more information? Did you build this with cmake or files from the `vs-build` directory of the OpenFAST repo?

**Comment by AngelCamargoUSP** [comment] 2021-01-18 22:29
Hello Bonnie! I build it with vs-build directory. I'm gonna try  now with another input file. I'll respond ASAP

**Comment by bjonkman** [comment] 2021-01-19 18:12
@AngelCamargoUSP , I noticed that the Simulink interface was overwriting error messages when OpenFAST returned a fatal error. For help figuring out why your model wasn't running properly, you can use this branch: https://github.com/bjonkman/openfast/tree/b/Simulink_errors

**Comment by AngelCamargoUSP** [comment] 2021-01-19 19:27
Thank you very much! I'm gonna check this material. I hope I can figure out what is wrong with the function. I tried with another inputs like you suggested but the same errors were returned.

**Comment by AngelCamargoUSP** [comment] 2021-01-19 21:04
@bjonkman this link seems to be broken. 
![image](https://user-images.githubusercontent.com/77124247/105092892-9f4efe00-5a80-11eb-98de-49b4d9fa6fdf.png)

**Comment by bjonkman** [comment] 2021-01-19 21:05
That branch was merged into dev quickly today, so use this instead: https://github.com/OpenFAST/openfast/tree/dev

**Comment by adrgambier** [comment] 2021-01-29 14:13
Hi,
I had a running compiled OpenFast 2.4 under Simulink (first version of OpenFast in Simulink that worked for me after changing CHANNEL_LENGTH). However, I received the same error from Simulink as described at the beginning here after the compilation of OpenFAST 2.5. The problem was that from version 2.4 to version 2.5 changes a little bit the input file for InflowWind. After updating the input file, OpenFast 2.5 under Simulink works fine! The changes are:

# Line 17: from Filename to Filename_Uni
# Line 18: from RefHt to RefHt_Uni
# Line 35: from RefHt to RefHt_Hawc
# Line 47: from PLExp to PLExp_Hawc
# Line 49: from InitPosition(x) to XOffset

Best regards
Adrian

**Comment by bjonkman** [comment] 2021-03-02 17:01
@rafmudaf , this issue can be closed.

**Closed** 2021-03-02 17:13 UTC
Labels: Type: Bug
