### ISSUE TITLE
Inconsistent Output and Assignment Error in fx_getMats Function during OC4 Wind Turbine Linearization in OpenFAST

### ISSUE THREAD

**Issue by whisperingkahuna** [OpenFAST/openfast#1622] opened 2023-06-13 08:31 UTC
**Bug description**
I am using the latest version of OpenFAST to carry out the linearization of the OC4 wind turbine. Three degrees of freedom are set as true, namely FlapDOF1, DrTrDOF, and GenDOF.

The wind speed is set at 18m/s. The option for CalcSteady is set as true, and the NLinTimes parameter is set to 36.

The process of linearization has been completed successfully, and the output has been generated as expected. However, when I try to execute the fx_getMats function from fx_getMats.m file in order to get the averaged matrices, I encounter the following error:

        fx_getMats(FileNames)
        Unable to perform assignment because the left and right sides have a different number of elements.

Error in fx_getMats (line 119)
matData.WindSpeed(iFile) = data(iFile).WindSpeed;

According to Jason, the following discrepancy in the .lin files could be causing the issue:

Current output: Wind Speed: *********** m/s
Expected output: Wind Speed: 18.0000 m/s

Even after trying again on a different computer with fresh files, the problem persists. Could this be a bug?

**Screenshots, if applicable**
Output screenshot
![plot_wind_2023-06-12_16-44-38](https://github.com/OpenFAST/openfast/assets/28399678/c35499e5-e6ab-4e1c-a8e4-890c5f22bd4a)

**OpenFAST Version**

![image (4)](https://github.com/OpenFAST/openfast/assets/28399678/d2994702-44b7-4307-a2b3-f02120480e0d)

**System Information (please complete the following information):**
 - OS: <Windows 11, 10>

**Additional context**
<linearization files for reference
[5MW_OC4Semi_WSt_WavesWN_lin files.zip](https://github.com/OpenFAST/openfast/files/11732524/5MW_OC4Semi_WSt_WavesWN_lin.files.zip).>

**Comment by jjonkman** [comment] 2023-06-13 12:38
Dear @whisperingkahuna,

Stars (***) would show up in an output if the internal value stored cannot be displayed in the internal Fortran format used for writing the output file.  I would not expect that you’d receive this issue with this wind speed output.  I’m not aware of a bug with this output, but perhaps something was introduced recently?

Can you also share your input files so that we can reproduce the error?
 
Best regards,

**Comment by whisperingkahuna** [comment] 2023-06-13 13:08
Dear @jjonkman jjonkman,
Thank you for your response.

Here are the files.

https://www.dropbox.com/s/detat90jx0pcv5x/OpenFast_linear.zip

**Comment by jjonkman** [comment] 2023-06-13 13:58
Dear @whisperingkahuna,

I was able to run your example using NREL's precompiled version of OpenFAST v3.5 and reproduce the issue where stars appear in place of the wind speed in the linearization output files.  I don't see any other stars appearing in the linearization or time-series output files, so, it appears that the bug is isolated only to the wind speed written to the linearization output file.

FYI: It looks like the input files you shared were from a different model than your original post; your original post had 36 linearization files whereas your input files generate only 2; regardless, the issue is the same in both.

@andrew-platt -- Any ideas?

Best regards,

**Comment by whisperingkahuna** [comment] 2023-06-13 17:36
Dear @jjonkman,

My apologies for the confusion caused by providing an incorrect .fst file version earlier. 

To further investigate the issue, I attempted to isolate whether CalcSteady was the cause. I deactivated this feature and carried out linearizations at two separate points. Unfortunately, the problem still persisted. I provided that file instead. I am glad that you could reproduce it.

Best regards,

**Comment by andrew-platt** [comment] 2023-06-13 19:57
This looks like a formatting issue in writing the `.lin` file.  I'll change the formatting and get the fix into release 3.5.1

I'll post a code fix for this here as well.

**Comment by whisperingkahuna** [comment] 2023-06-14 05:01
Dear @andrew-platt,

Thank you for your reply.

When I manually adjust the value to 18.0000 m/s, the fx_getMats function appears to operate properly. However, a new issue has emerged. The average matrices A, B, and C are presenting as follows:


Can you help me interpret or resolve this? Thanks in advance.

![image](https://github.com/OpenFAST/openfast/assets/28399678/b19e27f4-22c4-4b0c-ac00-2d79a5077621)

linearization files here for reference 
[pltform trans rot lin.zip](https://github.com/OpenFAST/openfast/files/11741728/pltform.trans.rot.lin.zip)

**Comment by whisperingkahuna** [comment] 2023-06-14 19:27
Dear @jjonkman ,

I have used the OpenFast linearization in Matlab Simulink with the following parameters.
Calstdy True
 DOFs used;
DrTrDOF
GenDOF
PtfmSgDOF
PtfmSwDOF
PtfmHvDOF
PtfmRDOF
PtfmPDOF
PtfmYDOF

Including the following damping terms:
Twr_Kdmp: 10000
Bld_Kdmp: 10000

Here is the output of this OpenFast time series.

![image (5)](https://github.com/OpenFAST/openfast/assets/28399678/566cb3ec-89ee-4466-be1c-3a82e838c86a)

The problem with .lin files was still there. 
Where,
Wind speed = *********.
So, I manually changed the Wind speed to 18.0000 m/s.
When I used the fx_getMats to get averaged matrix, it resulted in NaNs. 
However, when I used this old GetMats_f8.m function, I got the averaged matrix values, and there was no NaNs problem.
source: [GetMats_f8.zip](https://github.com/OpenFAST/openfast/files/11749814/GetMats_f8.zip)
It seems there are two problems, 
1) Wind speed=******* in .lin files 
2) After modifying the wind speed manually, fx_getMats not being able to generate average matrixes, whereas an old version can generate these matrixes.

Best regards,

**Comment by jjonkman** [comment] 2023-06-14 20:07
Dear @whisperingkahuna,

In the _pltform.trans.rot.lin.zip_ archive you shared above, the NaNs appear within the OpenFAST linearization files themselves, e.g., you can see the NaNs in _5MW_OC4Semi_WSt_WavesWN_platform_lin.SFunc.1.lin_, etc.  This would indicate the problem is not in in the fx_getMats script.  Where these NaNs generated by OpenFAST or in your conversion of the _.lin_ file to fix the issue with ***?

Best regards,

**Comment by whisperingkahuna** [comment] 2023-06-15 05:29
Dear @jjonkman, 
I double-checked the lin files I shared earlier, and they have NaNs. I am not sure what caused them. 
When I tried again; I renamed the wind speed values to 18.0000m/s and used fx_getMats, and it worked. This happened probably due to the presence of these lin files with NaNs in the Matlab work directory fx_getMats was referring to it instead of my desired lin files. 

Thank you for helping me solve this issue.

Best regards,

**Comment by andrew-platt** [comment] 2023-06-26 17:18
I dug into this bug a little bit.  The issue with the wind speed in the _.lin_ output file is that the wind speed is not getting correctly passed to `FAST_Lin.f90`.  I suspect this is an issue related to recent changes in the `InflowWind` data handling.

**Comment by andrew-platt** [comment] 2023-06-27 00:18
The underlying wind speed issue in the `.lin` file has been addressed in the rc-3.5.1 branch, and will be included in the 3.5.1 release.

**Closed** 2024-02-14 17:52 UTC
Labels: Type: Bug, Feature: Linearization
