### ISSUE TITLE
Dynamically change of the blade mass properties within a given simulation in OpoenFAST and ElastoDyn

### ISSUE THREAD

**Issue by LaurenceWETI** [OpenFAST/openfast#339] opened 2019-10-01 15:14 UTC
Dear OpenFAST developer,

@jjonkman

I’m trying to change blade mass properties dynamically within a given simulation #253. For this reason I tried to modify the blade element mass during the simulation by adding Subroutine AddMass to ElastoDyn.f90 as follow: 
```

END SUBROUTINE Coeff
!----------------------------------------------------------------------------------------------------------------------------------
!**********************************************************************************************************************************
!> This routine is used to add mass to blade elements at a given simulation time
SUBROUTINE AddMass(p)
!..................................................................................................................................

      ! Passed variables

   TYPE(ED_ParameterType),        INTENT(INOUT)    :: p                             !< Parameters of the structural dynamics module


      ! Local variables.


   INTEGER(IntKi)               :: J                                               ! Loops through nodes / elements.
   INTEGER(IntKi)               :: K                                               ! Loops through blades.

   !...............................................................................................................................
   ! Calculate the new blade element mass 
   !...............................................................................................................................

  print*,"Hello Laurence u r in Subroutine AddMass"

   DO K = 1,p%NumBl          ! Loop through the blades

  print*,"Hello Laurence u r in Blades Loop"

      DO J = 1,p%BldNodes    ! Loop through the blade nodes / elements


      ! Calculate the mass of the current element

  print*,"Hello Laurence u r in Nodes Loop"

         p%MassB(K,J) = 1.5*p%MassB(K,J)
         p%BElmntMass(J,K) = p%MassB(K,J)*p%DRNodes(J)                        ! Mass of blade element J


      ENDDO ! J - Blade nodes / elements

   ENDDO    ! K - Blades

END SUBROUTINE AddMass

```

Subroutine AddMass is called at a given time within the simulation in FAST_Prog.f90 as follow:
```

!...............................................................................................................................
   ! Time Stepping:
   !...............................................................................................................................         
   
   DO n_t_global = Restart_step, Turbine(1)%p_FAST%n_TMax_m1 
   
      ! call AddMass routine at given simulation time 
	  
	  IF (n_t_global == 100) THEN
	  print*,"Hello Laurence u r at simulation time 100"
			CALL AddMass(p_ED)
	  END IF
	
```

After that I could compile OpenFAST without errors. 
To check if the changing of blade element mass takes place, I performed the TEST 18 (5MW_Land_Dll_WTurb) with the new OpenFAST.exe and I compared the results with the original OpenFAST.exe. The results were identical for both models, and there are no remarkable changes in the results at the given time!
To test whether OpenFAST.f90 is calling Subroutine AddMass correctly or whether the DO Loop in Subroutine AddMass is working properly, some pop-up messages are printed when Subroutines are calling.
![cmd](https://user-images.githubusercontent.com/47774400/65974973-2c2a0e80-e46e-11e9-8478-9ada1355886b.JPG)
  
The above screenshot shows clearly that the program didn’t go through the DO Loop. I’m not sure if the ElastoDyn parameters type (p) are available for Subroutine AddMass at the given time or not? 
When the ElastoDyn parameters type (p) are defined at initialization and remains stored throughout the entire simulation, how can I assess this parameter within the simulation? And whether it’s possible to change this parameter after initialization?
Any help would be really appreciated!

Best regards

Laurence

**Comment by bjonkman** [comment] 2019-10-01 15:24
One thing that looks strange to me is that you are using `p_ED` in FAST_Prog.f90. I would expect it to be `Turbine(1)%ED%p`. If you added a `p_ED` type yourself, none of the variables would be initialized, so it either won't go through the loops, or it would give you segmentation faults.

**Comment by LaurenceWETI** [comment] 2019-10-02 11:44
Dear Bonnie,

Thank you very much for your quick response.
I do add a `p_ED` type by myself in the header of FAST_prog.f90, because I thought that the argument in Fortran Subroutine works in the same way as in Matlab Function, but obviously it seems not.
After I used `Turbine(1)%ED%p` in FAST_Prog.f90 it did work and it went through the loops and it changed the blade element mass.
Now I’m checking if the Blade Mode Shapes and the Flap- and Edge-stiffness are also changed with the changing of blade element mass.
Could you please keep this issue open? Because I’ll have for sure more questions relating to this topic in the future.

Best regards
Laurence

**Comment by bjonkman** [comment] 2019-10-17 15:10
One thing to keep in mind is that if you are changing any registry input files, you might need to build twice (the first time Visual Studio regenerates the *_Types.f90 files, but the code that depends on those types files doesn't necessarily build with the correct version of the *_Types.f90 file until the second build). That may be the cause of the first error you display (unless something else is incorrect).

One issue I see is that your `p%TwFAM1SHX` array doesn't appear to be the same size as the `InputFileData%TwFAM1Sh` array. You should allocate them to be the same size if you are going to set them equal to each other. Here's the allocation I see for the existing array:
```
CALL AllocAry  ( InputFileData%TwFAM1Sh,  PolyOrd-1, 'TwFAM1Sh'  , ErrStat, ErrMsg )
```
Yours is allocated to be one element larger.

**Comment by andrew-platt** [comment] 2019-10-17 16:46
If you are using the current `dev` branch, the build process for the _Types.f90 files has changed: they are no longer part of the standard build process.  Instead see this: https://raf-openfast.readthedocs.io/en/feature-registry_rework/source/dev/types_files.html

**Comment by LaurenceWETI** [comment] 2019-10-21 12:01
Dear OpenFAST Devloper,

I could change the mass of the blade elements within simulation, and I would like to discuss with you the result of the mass addition. 
I rised the mass of the blade elements by multiplying the mass density of each blade element with a factor of 1.5. The mass addition proceeded as a part of the Subroutine ED-CalcOutput by calling the Subroutine UpdateCoeff at a given simulation time (in my example at t = 0.5 [s]). I attached the ElastoDyn.f90 file to see all the modifications in my code.

[ElastoDyn.txt](https://github.com/OpenFAST/openfast/files/3750533/ElastoDyn.txt)

After compiling OpenFAST I performed Test 18 (5MW_Land_DLL_WTurb) and I plotted the blade element masses for the List of blade nodes that have strain gages BldGagNd in figure one, this signals (SpnMb) I generated by myself to see the physical-mass addition. In figure 2 I compared the rotor speed of each version of the OpenFAST and of the OpenFAST+AddMass function.

[Figure_1.pdf](https://github.com/OpenFAST/openfast/files/3750592/Figure_1.pdf)

[Figure_2.pdf](https://github.com/OpenFAST/openfast/files/3750624/Figure_2.pdf)

Actually, I expiated a continuous reduction of rotor speed after a mass addition of 1.5 for each blade element, but the figures didn’t show that! 
Is my expectation right? Did my implementation of the mass addition correct?  

Best regards
Laurence

**Comment by LaurenceWETI** [comment] 2019-10-22 14:31
@jjonkman @bjonkman 
One more question, I would like to expand the ElastoDyn.dat input file to use the increasing factor 
_AddMassF_ and the Time _AddMassT_ for mass addition as InputData, so I don’t have  to compile OpenFAST every time I need to change the time or the factor of mass addition: 
![Plot_1](https://user-images.githubusercontent.com/47774400/67296264-84da4d80-f4e8-11e9-8029-28414a3ceced.JPG)

I already add those input data and theirs corresponding parameters in ElastoDyn_Registry.txt and in ElastoDyn_IO.f90. 
I could after that compile OpenFAST, but when I start a simulation I've got this error:
![Plot_2](https://user-images.githubusercontent.com/47774400/67296285-8c99f200-f4e8-11e9-906e-9eb90c1a94c9.JPG)

**Comment by bjonkman** [comment] 2019-10-22 17:06
Are you sure you are reading the two new inputs from the file correctly? You added two new `CALL ReadVar()` lines and you put them after the space where it reads `PtfmYIner`?

**Comment by LaurenceWETI** [comment] 2019-11-11 15:20
Hello,

ist hat posible to use signals from ServoDyn in ElstoDyn? I see that there are signals generated in ElastoDyn to use in ServoDyn like this: 
 ```
  !...............................................................................................................................
   ! Outputs required for ServoDyn
   !...............................................................................................................................
   
   y%Yaw      = x%QT( DOF_Yaw)
   y%YawRate  = x%QDT(DOF_Yaw)
   y%YawAngle = x%QT( DOF_Yaw) + x%QT(DOF_Y)  !crude approximation for yaw error... (without subtracting it from the wind direction)   
   y%BlPitch  = u%BlPitchCom !OtherState%BlPitch
   y%LSS_Spd  = x%QDT(DOF_GeAz)
   y%HSS_Spd  = ABS(p%GBRatio)*x%QDT(DOF_GeAz)
   y%RotSpeed = x%QDT(DOF_GeAz) + x%QDT(DOF_DrTr)
```
Now I’m trying to do exact the opposite. I want to generate a signal in ServoDyn to use it in ElasoDyn.
To do that I defined first an output signal 
`y%BlPitchED(K) = p%BlPitchF(K)`
Then I allocated this signal in SrvD_OutputType data structure (y)
```
   CALL AllocAry( y%BlPitchED, p%NumBl, 'BlPitchED', ErrStat2, ErrMsg2 )
      CALL CheckError( ErrStat2, ErrMsg2 )
      IF (ErrStat >= AbortErrLev) RETURN
```
Afterthat I defended this output in ServoDyn_Registry.txt
`typedef	^	OutputType	ReKi	BlPitchED	{:}	-	-	"Commanded blade pitch angles (ElastoDyn)"	radians`
But now I don’t know what I’ve to do use this signal in ElstoDyn?
Thank you for your help

**Comment by jjonkman** [comment] 2019-11-11 16:05
Dear @LaurenceWETI,

 In the FAST / OpenFAST modularization framework, when modules are coupled together, the inputs and outputs should be consistent, i.e., the inputs to a given module should be derivable from the outputs of other modules.  So, if you wish to add an output to ServoDyn that becomes an input to ElastoDyn, you should define the output in ServoDyn, define the input in ElastoDyn, and then modify the OpenFAST glue code to transfer the ServoDyn output as an input to ElastoDyn.  For example of this, see how ServoDyn output BlPitchCom is transferred as an input to ElastoDyn.

Best regards,

**Comment by LaurenceWETI** [comment] 2019-11-18 08:23
@jjonkman  thank you for your quick response

**Comment by daansl1** [comment] 2021-07-14 15:25
Dear all,

@jjonkman 
I to have been trying to dynamically adjust parameters in OpenFAST and ElastoDyn, which I have done according to the example @LaurenceWETI so kindly supplied in his first comment in this issue. 

I have added the following routine to ElastoDyn.f90 to change GBRatio:

```
!----------------------------------------------------------------------------------------------------------------------------------
!> This routine changes the gearbox ratio
SUBROUTINE ChangeGBRatio(p)
!..................................................................................................................................

        ! Passed variables

    TYPE(ED_ParameterType),     INTENT(INOUT)   :: p    !< Parameters of the structural dynamics module

        ! Local variables.

    print*, "Changing GBRatio"
    print*, "GBRatio before change:",p%GBRatio
    p%GBRatio = 2*p%GBRatio
    print*, "GBRatio after change:",p%GBRatio

END SUBROUTINE ChangeGBRatio
``` 

In order to call the subroutine in the time loop I have added to 'FAST_Prog.f90' the following code:


```
   !...............................................................................................................................
   ! Time Stepping:
   !...............................................................................................................................         
   
TIME_STEP_LOOP:  DO n_t_global = Restart_step, Turbine(1)%p_FAST%n_TMax_m1 
      
      ! bjj: we have to make sure the n_TMax_m1 and n_ChkptTime are the same for all turbines or have some different logic here
      IF (n_t_global == 6400) THEN 
          print*, "Printing is successfull", n_t_global
          
            CALL ChangeGBRatio(Turbine(1)%ED%p)
      END IF 
```

Which works perfectly fine when I run OpenFAST from the command line, i.e. when I change the GBRatio, the GenSpeed changes immediately. However, I am using OpenFAST in a Simulink environment and the dynamic change does not occur when I use the S-function. 

I have tried calling 'ChangeGBRatio' from the subroutine FAST_Update(iTurb, NumInputs_c, NumOutputs_c, InputAry, OutputAry, ErrStat_c, ErrMsg_c) in 'FAST_library.f90' of the OpenFAST_Simulink-project, similarly to method used for the regular project. The project builds and the S-function is generated without any errors, however the change does not seem to happen during my Simulink run. 

```
REAL(ReKi)                            :: Outputs(NumOutputs_c-1)
   INTEGER(IntKi)                        :: i
   INTEGER(IntKi)                        :: ErrStat2                                ! Error status
   CHARACTER(IntfStrLen-1)               :: ErrMsg2                                 ! Error message  (this needs to be static so that it will print in Matlab's mex library)
                 
   
   IF (n_t_global == 6400) THEN 
          print*, "Printing is successfull", n_t_global
          
            CALL ChangeGBRatio(Turbine(1)%ED%p)
   END IF 
   
   IF ( n_t_global > Turbine(iTurb)%p_FAST%n_TMax_m1 ) THEN !finish 
```

How can I, similarly to solution for the regular OpenFAST-project, dynamically change the parameter?

If you would be able to help me or point me in the right direction that would be much appreciated. Thank you in advance.

Regards,

Daan

**Comment by jjonkman** [comment] 2021-07-14 18:19
Dear @daansl1 ,

I see that you are using `Turbine(1)%ED%p` in your `CALL` to SUBROUTINE `ChangeGBRatio()`, but turbine index `iTurb` is set to 0 (being zero-based) in _FAST_SFunc.c_.  Does your code work as expected if you change to `Turbine(iTurb)%ED%p`?

Best regards,

**Comment by daansl1** [comment] 2021-07-15 08:19
Dear @jjonkman ,

Thank you for your swift response. The change you suggested has done the trick, the parameter changes midsimulation. Thank you very much.

Best regards,

**Closed** 2021-07-15 14:12 UTC
Labels: Type: Enhancement
