### ISSUE TITLE
Trouble Opening FAST.sln to Set Up OpenFAST

### ISSUE THREAD

**Issue by mwh50** [OpenFAST/openfast#131] opened 2018-05-30 01:10 UTC
Hey all,

My apologies for the dumbness of this question.  I've been struggling for a while to set up OpenFAST without much luck.  I am following the instructions here on[ Building OpenFAST on Windows with Visual Studio](http://openfast.readthedocs.io/en/master/source/install/install_vs_windows.html), and I am stuck at step 2.5.2.4 - 2.5.2.7.  When I open the FAST.sln file, Visual Studio opens it and immediately becomes unresponsive while showing the screen below.
![image](https://user-images.githubusercontent.com/39747708/40688640-d2971ada-636c-11e8-8e91-bf16705df0ee.png)

I've tried to bypass this step by opening FAST.sln in Visual Studio.  I get past the "Upgrade Fast_Registry.vcxproj and MAP_d11.vcxproj" step, but when it comes to building the solution, I get a ton of errors.  The instructions say this is normal and that I need to build then restart to Visual Studio, but when I do nothing changes in terms of the errors.  The screen with the errors is shown below.
![image](https://user-images.githubusercontent.com/39747708/40693237-6366ad52-6384-11e8-9c32-a83d85708165.png)

Any help or advice would be greatly appreciated!  I'm an undergrad student without experience in this field, but I am very excited to learn!

**Comment by bjonkman** [comment] 2018-06-01 18:17
1. The first figure you show looks like it's trying to open in Visual Studio 2013, but the second has the icon for Visual Studio 2017. Did you install the Intel Fortran integrations for VS 2013 as well as 2017? 
2. I would take a look at the build logs. You can either just look at the text in the `output` window, (next to the `error list` window that is open) or you can search for "Build log written to" to find links to build logs for individual projects. You'll want to see which one has the first error to see what is causing the issue.

**Comment by mwh50** [comment] 2018-06-04 13:39
1.  I checked every way I know how and I don't I have VS 2013 installed.  I think the colors just inverted after VS 2017 crashed making it look like VS 2013.

2.  I've been working with the BuildLog as you suggested and the error that keeps on popping up goes as follows:

ifort /nologo .... (to a referenced f.90 file that changes for every error)
ifort: command line warning #10161: unrecognized source type 'Hampton\OpenFastV1\openfast\vs-build\FASTlib\\..\gitVersionInfo.h''; object file assumed
ifort: error #10273: Fatal error in C:\PROGRA~2\INTELS~1\COMPIL~1\windows\bin\intel64\fortcom, terminated by 0xc0000005

So I'm assuming that the problem is coming from Visual Studio not being able to read the C declarations in the header file "gitVersionInfo.h".  Any suggestions on how to fix that?  I haven't found anything online.

--Mike

PS: I attached the build log in case you want to see it.

[BuildLog.htm.pdf](https://github.com/OpenFAST/openfast/files/2068451/BuildLog.htm.pdf)

**Comment by sayerhs** [comment] 2018-06-04 14:09
@mwh50 `gitVersionInfo.h` is an auto-generated file and requires a working Git installation on the Windows system -- see [VS Build docs](https://openfast.readthedocs.io/en/dev/source/install/install_vs_windows.html). 

This comment in `modules-local/nwtc-library/src/NWTC_IO.f90` might also be useful

```
   ! VS build method for obtaining the git version info.
   ! This requires setting:
   !  1) GIT_INCLUDE_FILE = '$(ProjectDir)\..\gitVersionInfo.h' preprocessor option on this file or the project containing this file.
   !  2) Creating a prebuild event on the project file producing the resulting binary (i.e., FAST.exe) with the following command: ..\CreateGitVersion.bat
   !  3) The bat file, CreateGitVersion.bat, located in the vs-build folder of the openfast repository, which contains the git command used to obtain the git info
   !         @ECHO off
   !         SET IncludeFile=..\gitVersionInfo.h
   !
   !         <NUL SET /p IncludeTxt=#define GIT_VERSION_INFO '> %IncludeFile%
   !         FOR /f %%a IN ('git describe --abbrev^=7 --always --tags --dirty') DO <NUL SET /p IncludeTxt=%%a>> %IncludeFile%
   !         ECHO '>> %IncludeFile%
   !         EXIT /B 0
   !     This creates the gitVersionInfo.h file in the vs-build folder
```

**Comment by mwh50** [comment] 2018-06-04 15:12
Thank you very much Bonnie and Shreyas for your help.  Unfortunately I don't think I am experienced enough to understand what I should do going forward.  I have installed git for Windows, but I don't really understand what to the comments are telling me to do with it.

For 1): 
Do I add that line of code, with the full file path, after the exclamation points?  I actually see the file gitVersionInfo.h in my vs-build folder right now, though in the build log, it was referenced in a different folder.  (See screenshot at the bottom)

For 2):
Do I work in the command prompt to call Fast.exe then the ..\CreateGitVersion.bat ?

For 3):
Is this something I should do or is it just explaining what the git command would do?

I tried to follow the VS Build docs as closely as I could, and I didn't see any of this mentioned.  I also already had git installed for Windows, and used it to clone the OpenFAST repository when I initially downloaded OpenFAST.

Thanks again,
Mike 
![image](https://user-images.githubusercontent.com/39747708/40925573-0ac94bec-67e8-11e8-8b3b-0008367da2a4.png)

**Comment by bjonkman** [comment] 2018-06-04 15:35
@mwh50, 

You shouldn't have to change any code. The batch file is run as a pre-build event as part of a Visual Studio project file, and it looks like it ran because it created the `gitVersionInfo.h` file. Can you check what the contents of that file are? It should contain a single statement similar to this: 
```
#define GIT_VERSION_INFO 'v1.0.0-152-g22b77665' 
```

If you installed Git for Windows to run only from Git Bash, the .h file will contain an error, which may be why ifort isn't recognizing the source type. You need to make sure you select `Use Git from the Windows Command Prompt` when you install Git for Windows, otherwise the batch file won't run properly.

**Comment by mwh50** [comment] 2018-06-04 16:31
The gitVersionInfo.h file contains this:
![image](https://user-images.githubusercontent.com/39747708/40927982-310b6424-67ee-11e8-93f2-a73c5475d6c1.png)

You're 100% correct about me installing Git for Windows to run only from Git Bash, so I just installed it selecting `Use Git from the Windows Command Prompt` and I cloned a new OpenFAST Repository.  Unfortunately, nothing seemed to change.  I'm still getting the same gitVersionInfo.h file with the same Build Log.

--Mike
[BuildLog.htm.pdf](https://github.com/OpenFAST/openfast/files/2069117/BuildLog.htm.pdf)

**Comment by bjonkman** [comment] 2018-06-04 17:20
I would guess that Intel Fortran 2018 has decided that the included `.h` file isn't a Fortran source file. (Intel 2018 seems to be more strict about things than 2017 and earlier versions.) 

You might try adding `/source:gitVersionInfo.h` to the `FASTlib` project. (Right-click on `FASTLib` in the VS Solution Explorer window, select `Properties`, select `Configuration Properties->Fortran->Command Line` and type in the `Additional Options` box. You might need to add the full path name for gitVersionInfo.h (see the `All Options` box for example syntax).

**Comment by mwh50** [comment] 2018-06-04 17:57
Hmm that does sound like it would be a problem.  I went ahead and added `/source:gitVersionInfo.h` into the command line.  There aren't any full paths shown in the All Options box, so I wasn't able to try that.
![image](https://user-images.githubusercontent.com/39747708/40933145-9f614a0a-67fe-11e8-913f-0bd946b9467d.png)
Unfortunately, this doesn't fix the errors.  Thanks again for all the help you're giving me!

**Comment by ghaymanNREL** [comment] 2018-06-04 20:17
@mwh50,

Perhaps try manually changing the filename of gitVersionInfo.h to gitVersionInfo.f90
Then (Right-click on FASTLib in the VS Solution Explorer window, select Properties, select Configuration Properties->Fortran->Preprocessor   and change the filename in the Preprocessor Definitions section

**Comment by mwh50** [comment] 2018-06-07 20:36
Hey all,

Thank you Greg and Bonnie for all the help.  I've been working on this for a couple days, and I have finally broken through by basically redoing everything on as a different user on my computer...  Its not the perfect solution, but it resolves the problem with building.

However, when I try to run the OpenFAST regression tests as described [here](http://openfast.readthedocs.io/en/latest/source/testing/regression_test_windows.html#), all the tests except the WP_Stationary_Linear one fail as shown below.  
![image](https://user-images.githubusercontent.com/39747708/41124167-1a2f012e-6a6f-11e8-8f11-c71bc370a327.png)
Once again, sorry for not being able to figure this stuff out.  I searched lot on the wind.nrel.gov forum and I couldn't find anything really close to this.  Also, if this should go under a separate post, let me know and I can do that too!

--Mike

**Comment by rafmudaf** [comment] 2018-06-07 20:42
Mike,

Can you verify that those test cases actually ran? For example, look in `openfast\build\reg_tests\fast\AOC_WSt\AOC_WSt.log` and see if there is anything of interest. A good run will show something like this
```
 Timestep: 10 of 60 seconds. Estimated final completion at 15:23:48.
                                                                                                  
 Timestep: 20 of 60 seconds. Estimated final completion at 15:23:53.
                                                                                                  
 Timestep: 30 of 60 seconds. Estimated final completion at 15:23:54.
                                                                                                  
 Timestep: 40 of 60 seconds. Estimated final completion at 15:23:53.
                                                                                                  
 Timestep: 50 of 60 seconds. Estimated final completion at 15:23:52.
                                                                                                  
 Timestep: 60 of 60 seconds. Estimated final completion at 15:23:53.
```

Rafael

**Comment by jjonkman** [comment] 2018-06-07 20:45
Dear @mwh50,

Another possibility is that you've compiled OpenFAST in single precision whereas the values r-test is checking against are based on double precision and the tolerance of 1e-5 you are using is smaller than the difference between the single- and double-precision solutions.  You can always plot the time series to see how large the differences actually are.

Normally I'd recommend running OpenFAST in single precision, which runs faster than the double-precision version and is typically accurate enough for engineering applications.  But the saved r-test values are based on a double-precision solution.

Best regards,

**Comment by mwh50** [comment] 2018-06-07 21:01
Thank you both so much for the quick responses.  @rafmudaf I believe this is the document you are talking about?
![image](https://user-images.githubusercontent.com/39747708/41125811-949b96da-6a73-11e8-8237-1b25fd301927.png)
It does look quite different than what you put down though, so do you have any suggestions on what I'm doing wrong?  Also, my file tree looked a little different than the one you put out so here's a screenshot of where I got my file from.
![image](https://user-images.githubusercontent.com/39747708/41125916-dc432af2-6a73-11e8-977f-7bb4f8c116e9.png)

@jjonkman You are 100% right about me using single precision.  I'll go back and try that, and let you know if that fixes things!  My computer (and me) isn't the quickest, so that may take a bit.

**Comment by mwh50** [comment] 2018-06-08 14:40
I went ahead and did the tests with double precision and unfortunately I got the same result as before:
![image](https://user-images.githubusercontent.com/39747708/41163991-1449bd14-6b08-11e8-9c10-6fb149e9ba11.png)

A couple things to note: 
-I keep getting different file tree than the one @rafmudaf referenced, and I can't really find a .log file for either of the r-tests.  Specifically, when I get to the reg_tests folder, there is only the glue-codes folder shown below and nothing for fast.  Its making me think I am not actually running the tests.
![image](https://user-images.githubusercontent.com/39747708/41162137-05a74ad8-6b03-11e8-8e1a-88c24393984e.png)

-What I've done with the single or double precision solutions is compile them using visual studio using either "Release_Double" or "Release" on the solutions configuration.  I believe that's what you meant @jjonkman  but there's also a good chance I am wrong.

--Mike

**Comment by rafmudaf** [comment] 2018-06-08 16:03
@mwh50 I accidentally left out `glue-codes` in the path to the log file, so your file tree in the build directory is indeed correct. Also, the last line saying `OpenFAST terminated normally` means that the case did actually run.

**Comment by rafmudaf** [comment] 2018-06-08 16:14
Also, by default the double precision binary should be named `openfast_x64_Double.exe`. Did you rename it manually?

You can generate plots of the local vs baseline solutions by adding a couple of flags to the python script:
```
python manualRegressionTest.py ..\build\bin\openfast_x64[_Double].exe windows intel 1e-5 -n -p
```
This will prevent the actual execution of the test cases with `-n` and generate a series of html files containing plots with `-p`. The main file to open will be at `openfast/build/reg_tests/glue-codes/fast/regression_test_summary.html`. This may provide some insight into the problem.

**Comment by mwh50** [comment] 2018-06-08 18:54
@rafmudaf Ok that makes sense!  

As for the double precision binary, I never renamed it.  I mentioned it earlier, but I'm not 100% sure I'm really using double precision.  I just used the "Release_Double" solution configuration and thought that would get me to double precision.  

Also, I did what you said, and the plots are incredibly useful.  It seems to go along with what @jjonkman said that I just am not using the right precision.  My plots seem to be off a little but generally pretty close to what they should be. (Some examples below)
![screencapture-file-c-users-mhampton-regtest-openfast-build-reg_tests-glue-codes-fast-aoc_wst-plots-plots-html-2018-06-08-14_47_36](https://user-images.githubusercontent.com/39747708/41175537-652a25a2-6b2b-11e8-878d-99f183c62563.png)
I'll keep working on trying to get the double precision, but I should mention that the [instructions ](http://openfast.readthedocs.io/en/latest/source/testing/regression_test_windows.html)I'm using don't really mention a file named `openfast_x64_Double.exe`.

Thanks again,
Mike

**Comment by jjonkman** [comment] 2018-06-08 19:03
Dear @mwh50,

Indeed the results you are showing are quite consistent with the baseline solutions and you can feel comfortable that you've compiled OpenFAST successfully (if the plots for the other cases are similar).

I agree that selecting "Release" in the OpenFAST Visual Studio project will compile in single precision and "Release Double" will compile in double precision.  My guess is the results you are showing are slightly different due to a small change to the source code or small difference in the compiler between the two solutions.  Regardless, the results are quite consistent and you should feel comfortable to use the compiled executable in applications.

Best regards,

**Comment by mwh50** [comment] 2018-06-08 19:18
Awesome!  Thank you so much!

--Mike

**Comment by jjonkman** [comment] 2018-06-08 19:18
Can we close this issue now?

**Comment by mwh50** [comment] 2018-06-08 19:20
Sure!

**Closed** 2018-06-08 19:21 UTC
Labels: question, visual-studio, windows

**Comment by ghaymanNREL** [comment] 2018-06-10 13:50
I noticed that Mike's new install has no spaces in his OpenFAST-related file paths, where as his original installation contained a space.  Does anyone have a working Windows installation with a path containing a space?

**Comment by bjonkman** [comment] 2018-06-11 15:16
@ghaymanNREL: I don't have spaces in my path names, but the Visual Studio files you have use relative paths, so I don't think that would be a problem. We did notice that the FAST Registry has issues with include paths that contain spaces (which would probably be a problem only with cmake, which uses absolute paths). We fixed that problem in https://github.com/rafmudaf/openfast/pull/6.

**Comment by tilucas97** [comment] 2020-03-31 02:27
Hello!

As Mike, all my tests failed, however, the resulted plots seem similar to his plots. I also tried single and double precision.
I'm using Python version 3.8 and I'm using cmd instead of Anaconda.
Other software data: Win10, VS 2015, Fortain 2017.

Do you think it should be ok as for Mike? 

Thank you very much for your disponibility,
Tiago 

Images:
![Test_1](https://user-images.githubusercontent.com/62906201/77980189-97aa4700-72fe-11ea-8b72-36e302d11583.png)
![Test_2](https://user-images.githubusercontent.com/62906201/77980452-3c2c8900-72ff-11ea-8f7c-67cac106242a.png)
![Test_3](https://user-images.githubusercontent.com/62906201/77980460-3fc01000-72ff-11ea-81be-e67c103a3821.png)

**Comment by jjonkman** [comment] 2020-03-31 02:50
Dear Tiago,

Yes, I agree that your results you are quite consistent with the baseline solutions and you can feel comfortable that you've compiled OpenFAST successfully (if the plots for the other cases are similar)

Best regards,

**Comment by tilucas97** [comment] 2020-03-31 12:30
Great! Thank you

Best regards,
