### ISSUE TITLE
Implementation of variable blade input properties in OpenFAST

### ISSUE THREAD

**Issue by LaurenceWETI** [OpenFAST/openfast#253] opened 2019-02-27 11:54 UTC
Hello everyone, 
@rafmudaf 
@DavidSchlipf

I'm working on a project that based on changing of inertia moment of rotor blades of wind turbine by shifting a fluid mass between two accumulators in rotor blade (for more information about the project see the attachment)
[Presentation_27_02_2019.pdf](https://github.com/OpenFAST/openfast/files/2910124/Presentation_27_02_2019.pdf)

Currently, FAST is not designed for simulating variable blade inertias. I.e. ElastoDyn reads only one blade input file for each blade at the beginning of the simulation, and these input files are not changing during the simulation. If the behaviour of a WT with variable blade inertia is to be simulated, FAST should be able to read different blade input file for each simulation step.
My questions:
-	Are changing blade properties already addressed in OpenFAST, e.g. lcing etc.?
-	Are these changes in general feasible?
-	Anyone have an advice how this should be implemented?
Any help would be really appreciated!

Best Regards
Laurence Alhrshy

**Comment by jjonkman** [comment] 2019-02-27 19:37
Dear @LaurenceWETI,

Without changing the source code, it is not possible in OpenFAST to change the blade mass properties dynamically within a given simulation.  There was a discussion on our forum some time ago about how to implement time-dependent stiffness changes within a given simulation e.g. as a result of ply delamination: https://wind.nrel.gov/forum/wind/viewtopic.php?f=7&t=1441&p=6492 (and this discussion is equally valid to changing blade mass instead of stiffness).

Blade icing is typically modeled in OpenFAST by increasing the blade mass (and perhaps using different masses between the blades to model an imbalance) and modifying the airfoil lift/drag data (modified based on the roughness caused by ice accretion) as discussed briefly in the following forum topic: https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=1064&p=8802.  But this is typically done with different masses and airfoil properties between separate simulations rather than dynamically within a given simulation.

I hope that helps.

Best regards,

**Comment by rafmudaf** [comment] 2019-03-01 20:46
@jjonkman @LaurenceWETI I'm closing this issue as the question seems to be answered. Please reopen if needed.

**Closed by rafmudaf** 2019-03-01 20:46 UTC

**Comment by LaurenceWETI** [comment] 2019-03-04 09:00
Thank you very much for the quick response. I’ll continue to work on this subject and I’ll keep you update.
