### ISSUE TITLE
Regression Tests - Python and Aerodyn15

### ISSUE THREAD

**Issue by bmazetto** [OpenFAST/openfast#197] opened 2018-10-21 00:01 UTC
Dear developers and OpenFast users,

I’m using Ubuntu on Windows 10 and I’ve built OpenFAST following the tutorial “Building OpenFAST with Cmake on Linux”. I’ve tried to run the regression tests manually, using the Python program, but all of the cases failed. I guess I may be using the wrong positional arguments. Could you give an example? 

![image](https://user-images.githubusercontent.com/44245549/47261664-8246b180-d4aa-11e8-8b95-d599e5c69193.png)

As the first approach didn't work, I've used the CTest procedure. Now, half of my tests failed and I’ve noticed that most of them were using AeroDyn15. Could you see the same correlation? Did I forget to do something during the installation or before running the tests?

![image](https://user-images.githubusercontent.com/44245549/47261674-ccc82e00-d4aa-11e8-8970-3bbfe77effd3.png)

Best regards, 
Bruno.

**Comment by rafmudaf** [comment] 2018-10-29 21:40
Hi @bmazetto,

Its suspicious that all of the 5MW cases failed. Is the DISCON controller located in the correct place? Check out this section of the documentation to verify that: https://openfast.readthedocs.io/en/master/source/testing/regression_test.html#ctest-configuration.

Rafael

**Comment by rafmudaf** [comment] 2018-11-07 18:49
@bmazetto I'm closing this issue since its gone silent but feel free to reopen as needed.

**Closed by rafmudaf** 2018-11-07 18:49 UTC
Labels: Type: Testing

**Comment by lenhou** [comment] 2019-04-12 09:45
Hi @rafmudaf,

I have exactly the same issue here, but I don't know what I can do to correct it.
![test result](https://user-images.githubusercontent.com/49435712/56026854-9c6d9800-5d47-11e9-8837-665660dfe20f.jpeg)

I have also followed the instruction of the documentation and the DISCON controllers are located in the following folders as the NOTE of README.md for r-test: 
    `openfast/build/reg_tests/glue-codes/openfast/5MW_Baseline/ServoData/DISCON.dll`
   `openfast/build/reg_tests/glue-codes/openfast/5MW_Baseline/ServoData/DISCON_ITIBarge.dll`
    `openfast/build/reg_tests/glue-codes/openfast/5MW_Baseline/ServoData/DISCON_OC3Hywind.dll`

By the way, there is maybe an inconsistent description of the location of DISCON controllers in the documentation. 

In section 5.2.2.3 of the online OpenFast documentation (https://openfast.readthedocs.io/en/master/source/testing/regression_test.html#ctest-configuration), which says that the DISCON controllers must exist in the following location:
`openfast/build/reg_tests/glue-codes/openfast/5MW_Baseline/ServoDyn/DISCON.dll`
`openfast/build/reg_tests/glue-codes/openfast/5MW_Baseline/ServoDyn/DISCON_ITIBarge.dll`
`openfast/build/reg_tests/glue-codes/openfast/5MW_Baseline/ServoDyn/DISCON_OC3Hywind.dll`

But it is different from the location (../ServoData instead of ../ServoDyn) indicated in the README.md for r-test, which may cause confusion.

Are there any hints or possible solutions for this situation?

Thank you.

Regards,
Len
