### ISSUE TITLE
OpenFAST with linux

### ISSUE THREAD

**Issue by caroledaniel** [OpenFAST/openfast#402] opened 2020-02-27 13:25 UTC
Hello, i'm using ubuntu 18 to install OpenFAST. in the documentation, it's written that i need to clone the tests(pFUnit and the r-test). do i need to clone them in 'home' directory or OpenFAST?and if in OpenFAST, which directory? thank you
@NRELAdmin  @michaelasprague

**Comment by jjonkman** [comment] 2020-02-27 13:50
This issue appears to be a duplicate of #401; so, I'm closing this issue.

**Closed by jjonkman** 2020-02-27 13:51 UTC
