### ISSUE TITLE
compiling problem

### ISSUE THREAD

**Issue by dorsamgh** [OpenFAST/openfast#2148] opened 2024-04-07 22:53 UTC
Hello, I hope you're doing well. I've run into a problem compiling software. As per the structure described, I've installed the required items. However, as shown in the picture, the term IFORT is not present next to the FAST project, and I feel that this is why I'm not obtaining the output exe file. If possible, could you guide me? Thank you.

![image](https://github.com/OpenFAST/openfast/assets/60191807/5567fecf-0689-4e69-a9a4-363fa2b1a13b)

**Comment by dorsamgh** [comment] 2024-04-09 12:48
Dear @jjonkman ,
Thank you for your response. I have read the solution mentioned [here](https://github.com/OpenFAST/openfast/issues/328#issuecomment-642907384). However, I did not understand it. In fact, I have both the 2019 version of VS Code and the 2022 version. With the 2019 version, my problem was that 3 out of 5 projects were not accessible, which, according to the mentioned solution, was resolved by reloading two of them. However, the FAST project still remains incompatible. 
![image](https://github.com/OpenFAST/openfast/assets/60191807/32c30f9d-04de-4b3a-8aba-dc3a8bce843b)

**Comment by dorsamgh** [comment] 2024-04-09 15:55
I redownloaded the files from https://github.com/OpenFAST/openfast, and the problem of the files being INCOMPATIBLE was resolved. However, after building in VS Code 2019 version, I encountered these errors.
![image](https://github.com/OpenFAST/openfast/assets/60191807/2531c8c2-ae9b-4edb-bf07-e3cd051818a1)

**Comment by jjonkman** [comment] 2024-04-10 18:33
Dear @dorsamgh,

Regarding the MKL errors, see a similar question asked and answered here: https://github.com/OpenFAST/openfast/issues/1249.

Best regards,

**Comment by dorsamgh** [comment] 2024-04-10 21:44
Dear @jjonkman,
thanks again for your response. i install the Intel® oneAPI Math Kernel Library (oneMKL) and after that, I was able to correctly compile the project and obtain the .exe file located at C:\Users\dmahd\Desktop\openfast-main\build\bin\openfast_x64.exe. Now, I want to use this file to simulate the IEA-15-240-RWT-UMaineSemi wind turbine, but I encountered the following error. Can you guide me in this matter as well? Thank you.
![image](https://github.com/OpenFAST/openfast/assets/60191807/70fc96d5-37db-4413-9959-a2be546c0f9f)

**Comment by jjonkman** [comment] 2024-04-10 21:47
Dear @dorsamgh,

It looks like your input file(s) are not formatted properly for the version of OpenFAST you are running.  The input file changes with each release of OpenFAST are documented here: https://openfast.readthedocs.io/en/main/source/user/api_change.html.  And as with any input file formatting issue, I would enable the `Echo` option to debug.

Best regards,

**Comment by dorsamgh** [comment] 2024-04-10 22:19
i enabled the Echo option and this is the result:

This file of echoed input was generated by OpenFAST on 11-Apr-2024 at 01:36:28.

Data from OpenFAST primary input file "IEA-15-240-RWT-UMaineSemi.fst":


               FTitle         - File Header: File Description (line 2)
  "IEA 15 MW offshore reference model on UMaine VolturnUS-S semi-submersible floating platform"

            T  Echo           - Echo input data to <RootName>.ech (flag)
               AbortLevel     - Error level when simulation should abort (string)
  "FATAL"
   6.0000E+01  TMax           - Total run time (s)
   2.5000E-02  DT             - Recommended module time step (s)
            2  InterpOrder    - Interpolation order for inputs and outputs {0=nearest neighbor ,1=linear, 2=quadratic} (-)
            0  NumCrctn       - Number of corrections{0=explicit calculation, i.e., no corrections} (-)
   9.9999E+04  DT_UJac        - Time between calls to get Jacobians (s)
   1.0000E+06  UJacSclFact    - Scaling factor used in Jacobians (-)

            1  CompElast      - Compute structural dynamics (switch) {1=ElastoDyn; 2=ElastoDyn + BeamDyn for blades}
            1  CompInflow     - inflow wind velocities (switch) {0=still air; 1=InflowWind}
            0  CompAero       - Compute aerodynamic loads (switch) {0=None; 1=AeroDyn}
            1  CompServo      - Compute control and electrical-drive dynamics (switch) {0=None; 1=ServoDyn}
            1  CompHydro      - Compute hydrodynamic loads (switch) {0=None; 1=HydroDyn}
            0  CompSub        - Compute sub-structural dynamics (switch) {0=None; 1=SubDyn}
            3  CompMooring    - Compute mooring system (switch) {0=None; 1=MAP; 2=FEAMooring; 3=MoorDyn; 4=OrcaFlex}
            0  CompIce        - Compute ice loads (switch) {0=None; 1=IceFloe}
            0  MHK            - MHK turbine type (switch) {0=Not an MHK turbine; 1=Fixed MHK turbine; 2=Floating MHK turbine}

   9.8100E+00  Gravity        - Gravitational acceleration (m/s^2)
   1.2250E+00  AirDens        - Air density (kg/m^3)
   1.0250E+03  WtrDens        - Water density (kg/m^3)
   1.4640E-05  KinVisc        - Kinematic viscosity of working fluid (m^2/s)
   3.3500E+02  SpdSound       - Speed of sound in working fluid (m/s)
   1.0350E+05  Patm           - Atmospheric pressure (Pa)
   1.7000E+03  Pvap           - Vapour pressure of working fluid (Pa)
   2.0000E+02  WtrDpth        - Water depth (m)
   0.0000E+00  MSL2SWL        - Offset between still-water level and mean sea level (m)

               EDFile         - Name of file containing ElastoDyn input parameters (-)
  "IEA-15-240-RWT-UMaineSemi_ElastoDyn.dat"
               BDBldFile(1)   - Name of file containing BeamDyn blade 1input parameters (-)
  ""
               BDBldFile(2)   - Name of file containing BeamDyn blade 2input parameters (-)
  ""
               BDBldFile(3)   - Name of file containing BeamDyn blade 3input parameters (-)
  ""
               InflowFile     - Name of file containing inflow wind input parameters (-)
  "../IEA-15-240-RWT/IEA-15-240-RWT_InflowFile.dat"
               AeroFile       - Name of file containing aerodynamic input parameters (-)
  "../IEA-15-240-RWT/IEA-15-240-RWT_AeroDyn15.dat"
               ServoFile      - Name of file containing control and electrical-drive input parameters (-)
  "IEA-15-240-RWT-UMaineSemi_ServoDyn.dat"
               HydroFile      - Name of file containing hydrodynamic input parameters (-)
  "IEA-15-240-RWT-UMaineSemi_HydroDyn.dat"
               SubFile        - Name of file containing sub-structural input parameters (-)
  "none"
               MooringFile    - Name of file containing mooring system input parameters (-)
  "IEA-15-240-RWT-UMaineSemi_MoorDyn.dat"
               IceFile        - Name of file containing ice input parameters (-)
  "none"

            F  SumPrint       - Print summary data to <RootName>.sum (flag)
   1.0000E+01  SttsTime       - Amount of time between screen status messages (s)
   9.9999E+04  ChkptTime      - Amount of time between creating checkpoint files for potential restart (s)
               DT_Out         - Time step for tabular output (s)
  "default"
   0.0000E+00  TStart         - Time to begin tabular output (s)
            1  OutFileFmt     - Format for tabular (time-marching) output file(s) {0: uncompressed binary and text file, 1: text file [<RootName>.out], 2: compressed binary file [<RootName>.outb], 3: both text and compressed binary, 4: uncompressed binary <RootName>.outb]; add for combinations) (-)
            T  TabDelim       - Use tab delimiters in text tabular output file? (flag)
               OutFmt         - Format used for text tabular output (except time).  Resulting field should be 10 characters. (-)
  "ES10.3E2"

            F  Linearize      - Linearization analysis (flag)
            F  CalcSteady     - Calculate a steady-state periodic operating point before linearization? (flag)
            3  TrimCase       - Controller parameter to be trimmed {1:yaw; 2:torque; 3:pitch} (-)
   1.0000E-03  TrimTol        - Tolerance for the rotational speed convergence (-)
   1.0000E-02  TrimGain       - Proportional gain for the rotational speed error (>0) (rad/(rad/s) for yaw or pitch; Nm/(rad/s) for torque)
   0.0000E+00  Twr_Kdmp       - Damping factor for the tower (N/(m/s))
   0.0000E+00  Bld_Kdmp       - Damping factor for the blades (N/(m/s))
            2  NLinTimes      - Number of times to linearize (-) [>=1]

            1  LinInputs      - Include inputs in linearization (switch) {0=none; 1=standard; 2=all module inputs (debug)}
            1  LinOutputs     - Include outputs in linearization (switch) (0=none; 1=from OutList(s); 2=all module outputs (debug))
            F  LinOutJac      - Include full Jacabians in linearization output (for debug) (flag)
            F  LinOutMod      - Write module-level linearization output files in addition to output for full system? (flag)

            2  WrVTK          - Write VTK visualization files (0=none; 1=initialization data only; 2=animation; 3=mode shapes)
            2  VTK_Type       - Type of  VTK visualization data: (1=surfaces; 2=basic meshes (lines/points); 3=all meshes)
            T  VTK_fields     - Write mesh fields to VTK data files? (flag)
   1.0000E+01  VTK_fps        - Frame rate for VTK output(fps)


as the version of OpenFAST that i used is Unversioned, how can I prepare the input files to be compatible with this version?

**Comment by jjonkman** [comment] 2024-04-10 23:53
There are separate Echo files for each input file.  In your previous message, the issue is with your InflowWind input file.  So you should enable Echo there and compare to your input file to see what is being read incorrectly.

You downloaded some version of the OpenFAST source code; which version was that?  (If you downloaded the most recent main branch, this would be OpenFAST v3.5.2.)  You should compare this to the version your input files are compatible for.  Either use an executable compatible with the version of your input files or upgrade the input files to the version of OpenFAST you are using.

**Comment by dorsamgh** [comment] 2024-04-11 08:50
thanks, this is the inflowind echo file:

Echo file for InflowWind input file: .\../IEA-15-240-RWT/IEA-15-240-RWT_InflowFile.dat
------- InflowWind v3.01.* INPUT FILE -------------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
IEA 15 MW Offshore Reference Turbine                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
---------------------------------------------------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
 True            = Echo                
 1               = WindType            
 0.0             = PropagationDir      
 0.0             = VFlowAng            
 0.0             = VFlowAng            

and i downloaded the source code from [here](https://github.com/OpenFAST/openfast) and i have the input files of IEA-15-240-RWT-UMaineSemi wind turbine from [here](https://github.com/IEAWindTask37/IEA-15-240-RWT)

**Comment by dorsamgh** [comment] 2024-04-11 09:00
I downloaded the source code from [here](https://github.com/OpenFAST/openfast) and got the exe file from there. and also downloaded the [IEA-15-240-RWT](https://github.com/IEAWindTask37/IEA-15-240-RWT) again. 
now I got another error with running the program.


![image](https://github.com/OpenFAST/openfast/assets/60191807/8084ff3a-cc13-440a-9d39-994a4394f1e9)

**Comment by jjonkman** [comment] 2024-04-11 13:00
Dear @dorsamgh,

The OpenFAST version of the IEA Wind 15-MW reference wind turbine models is documented in the release notes: 
https://github.com/IEAWindTask37/IEA-15-240-RWT/blob/master/ReleaseNotes.md.

Your new error was asked and answered in the following OpenFAST issue: https://github.com/OpenFAST/openfast/issues/1398.

I'm going to close this issue now as the original issue has been solved.  Please search OpenFAST Issues, Discussions, or our forum (https://forums.nrel.gov/) before posting new questions and start a new issue if you can't find the answer.

Best regards,

**Closed by jjonkman** 2024-04-11 13:00 UTC
Labels: System: Visual Studio, Compiler: Intel, Type: Compiling Question
