### ISSUE TITLE
Circulation solving method in OLAF

### ISSUE THREAD

**Issue by robytian** [OpenFAST/openfast#1465] opened 2023-02-22 02:38 UTC
Dear all
@ebranlard  @jjonkman 
I want to conduct secondary development for OLAF module, especially for the calculation of blade bound circulation. Could you please tell me the specific code location? The large amount of code is a little difficult for me.

In particular, I would like to take van A.Grrel's approach and I would like to know where his approach is applied in OLAF (Aero module).
![OLAF](https://user-images.githubusercontent.com/86820784/220506192-797898d4-5796-4220-9fc0-821e889a59a5.png)
All I need is the part that iterates to update the bound circulation based on the lift coefficient. (Obtain blade information, give the initial bound circulation, look up the table, calculate the bound circulation, iterate, output the blade bound circulation).
Thank you so much!

**Comment by ebranlard** [comment] 2023-02-22 05:15
Hi @robytian 
The iterative for the circulation solving, using the method of van Garrel is found here: 
https://github.com/OpenFAST/openfast/blob/dev/modules/aerodyn/src/FVW_Wings.f90#L312
I hope that helps.

**Comment by robytian** [comment] 2023-02-24 08:46
Hi @ebranlard
I'd like to ask you a few more questions, which I hope you can answer.
1.Did the code location you gave me last time include this theoretical part? [https://openfast.readthedocs.io/en/main/source/user/aerodyn-olaf/OLAFTheory.html#cl-based-iterative-method](url)  Is there any other.f90 needed?
2.Can two tests, "EllipticalWing_OLAF" and "HelicalWake_OLAF", output blade circulation and wake velocity field separately? Or do I need to implement the output by modifying WakeMod[3] in AeroDyn15 with OLAF integration?
3.I don't care about the structure, servo control and other modules given in openfast, I just want to achieve blade circulation calculation and helix wake output, is it possible to select "HelicalWake_OLAF" as a test?
4.If I want to model NREL5MW or IEA15MW, do I have to re-model it in "HelicalWake_OLAF"? Or do you need to model in OPENFAST 5MW_Baseline?
Thank you very much!
Best wishes

**Comment by ebranlard** [comment] 2023-02-24 19:19
Hi, 
Here are some answers to your questions:
1. Yes, the code implements exactly this theory, and the link I provided, form the line I pointed to to the bottom, is the code that implement the iteration algorithm. The most important piece of code that is not in this function is the computation of the Cl as function of angle of attack, `AFI_ComputeAirfoilCoefs`, which is part of the file `AirfoilInfo.f90`. 
2. I'm not sure I fully understand your question. AeroDyn can output the circulation along the blade using [Blade nodal outputs](https://openfast.readthedocs.io/en/main/source/user/aerodyn/input.html#sample-nodal-outputs-section) and the variable `Gam`. OLAF can output velocity fields using the [grid outputs](https://openfast.readthedocs.io/en/main/source/user/aerodyn-olaf/InputFiles.html#output-options). OLAF is selected using WakeMod=3
3. Yes, HelicalWake OLAF is a good test case for that. The best, when you only care about aerodynamics is to use the aerodyn driver. You'll find the HelicalWake test case for the aerodyn driver [here](https://github.com/OpenFAST/r-test/tree/main/modules/aerodyn/ad_HelicalWakeInf_OLAF).
4. If you want to model a realistic turbine, you'll have to go through the process highlighted in the [guidelines](https://openfast.readthedocs.io/en/main/source/user/aerodyn-olaf/RunningOLAF.html#guidelines). We do not provide OLAF input files for the NREL-5MW or IEA15MW (we might provide those in the future). All the input files you see on the `r-test` are only example files for testing purposes and are not intended to be used directly. 
I hope that helps!

**Comment by robytian** [comment] 2023-03-13 13:29
Hi @ebranlard 
After several days of simulation and modeling, in addition to the above questions, I also want to consult some other questions, please forgive me.

I modeled 5MW wind turbine according to ["ad_HelicalWakeInf_OLAF".](https://github.com/OpenFAST/r-test/tree/main/modules/aerodyn/ad_HelicalWakeInf_OLAF)The following problems were found:

1.The **WakeRegParam** shown [here](https://openfast.readthedocs.io/en/main/source/user/aerodyn-olaf/OLAFTheory.html#time-evolution-of-the-regularization-parametercore-spreading-method) in the manual does not exist in the OLAF [test.](https://github.com/OpenFAST/r-test/blob/55384eda96d626596efe735bcb2b51cf39e52476/modules/aerodyn/ad_HelicalWakeInf_OLAF/Helix_OLAF.dat#L27) Instead of **WakeRegFactor** and **WingRegFactor**, I would like to know what these two parameters should be set to for NREL 5MW wind turbine？

2.Based on the above problems, I want to know how the initial vortex core radius **rc0** is calculated?

3.The Regularization [parameters](https://openfast.readthedocs.io/en/main/source/user/aerodyn-olaf/RunningOLAF.html#guidelines) here state:
(1)Does WakeRegFactor=0.6 correspond to the formula given [here,](https://openfast.readthedocs.io/en/main/source/user/aerodyn-olaf/InputFiles.html#wake-regularization-and-diffusion-options) I wonder which value is multiplied by 0.6? How to understand **Deltar is the length of the spanwise station**?

(2)Here[(Regularization parameters)](url) the manual recommends **CoreSpreadEddyVisc=1000** and and [here](https://openfast.readthedocs.io/en/main/source/user/aerodyn-olaf/InputFiles.html#wake-regularization-and-diffusion-options) **The default value is 100**.

4.The calculation of **deltat**, **Ttarget**, **ntarget,distance**
(1)The **deltat** calculation formula is given [here.](https://openfast.readthedocs.io/en/main/source/user/aerodyn-olaf/RunningOLAF.html#guidelines) If I use NREL5MW fan, can it be understood as **deltat=1/12.1**, and the 5MW turbine default speed is 12.1rpm.
(2)It is pointed out here [(Wake length and number of panels)](https://openfast.readthedocs.io/en/main/source/user/aerodyn-olaf/RunningOLAF.html#guidelines) that there is no turbulence simulation ka=1.5, and there is turbulence simulation ka=1. I would like to know how the current test reflects whether my simulation is turbulence simulation or not.
(3)Based on (2), I want to simulate the wake region of 10 times the rotor diameter, then the calculation formula is as follows:
(10×126)/(11.4×(1-ka×a)),right?
(4)**ntarget,distance** equals **Ttarget** in (3) divided by **deltat** in (1) , right?
According to the above calculation,the **deltat is 0.083** the **total simulation time** is about 221s, and **ntarget,distance** is 2674. However, the calculation will stop at 186s, and the calculation does not reach 10 times the length of impeller. I wonder why?

5.Figure 1 and Figure 2 are completely different results from my two simulations, and Figure 3 is what I want to achieve.I want to know which parameters to adjust in the example to get the perfect helix and velocity field cloud picture.
![image](https://user-images.githubusercontent.com/86820784/224713101-ff740447-8a40-4d39-a5e3-4a846fcbec60.png)
figure1
![cdcd84abb8825ae902d19fc5d7aa6d2](https://user-images.githubusercontent.com/86820784/224712944-7c20328a-5fdc-4dfe-acfd-2c21cd5f812e.png)
figure2
![b91bc2a83e97e0a92761f1e6f701d29](https://user-images.githubusercontent.com/86820784/224712027-72092325-334d-4717-a2a8-a65e27cbb73b.png)
figure3

**Comment by ebranlard** [comment] 2023-03-14 19:21
Hi @robytian 

I don't have the time to go into all of your questions in details, but it seems like you are making progress. 

1-3  We indeed switched from "RegParam" to "RegFactor" and some places of the documentation needs updating, but they are the same thing, so you can replace "Param" by "Factor" in the definitions of rc here: 
https://openfast.readthedocs.io/en/dev/source/user/aerodyn-olaf/InputFiles.html#wake-regularization-and-diffusion-options
`Delta r` is the distance between two aerodyn nodes. 

4. If your simulation stops at 186s is likely because the .fst file stops at 186s, no? or does the simulation crash? 
The python script in the guidelines will help you set the parameters according to the equations of the guidelines. 

5.  If you want pure helices, then you can turn off the wake roll up by setting `FreeWakeStart ` to a very large value. Note that the wake won't be physical, but you'll get the perfect helix if that's what you are after. 

I can see that you have nNWPanelsFree to default. You can try to set it according to the guidelines, it will make the end of the wake less "messy". 

In Paraview, make sure to "rescale" the range of your colorscale for the velocity and the circulation (Paraview by default will set the range at t=0). 

To speed up the computation, you don't need to output the VTK and velocity fields at each time step. 


I hope that helps,

Emmanuel

**Comment by robytian** [comment] 2023-03-27 07:08
Hi @ebranlard 

Recently, I made a comparison on the software using the free vortex wake method. The wind turbine model is NREL-5MW, the **wind speed is 10m/s**, the **rotor speed is 10RPM**, the **DT is set to 0.1**, the **total simulation time is 300s**, and the panels of **nNWPanels are set to 3000**, while the rest are not set. It always stops at 113s (Instead of stopping the calculation, the calculation is done), I don't know why.

In addition, this is the velocity field distribution calculated and simulated by me. You can see that the wind speed distribution simulated by OLAF is completely opposite to that of Qblade. In my cognition, Qblade may be more consistent with the velocity distribution. What's the reason, I wonder?

I opened the visualization in paraview and selected the y distribution at x=100m and z=90m.
![image](https://user-images.githubusercontent.com/86820784/227865829-37b7d721-f08d-4503-ba17-16bf39f2a4be.png)

Here are the parameters I set in OLAF:
![image](https://user-images.githubusercontent.com/86820784/227865978-c9b38d5c-1bc3-41a6-95d5-e028825540f5.png)
![image](https://user-images.githubusercontent.com/86820784/227866072-b3fce451-f6fe-41b6-990e-645adafc6d79.png)

**Comment by ebranlard** [comment] 2023-08-24 17:25
Something might be wrong in the postprocessing, because the VTK figure of the wake you showed earlier has a wake deficit in the near wake that makes sense (double hump shape). In Figure 8 of [this paper](https://doi.org/10.5194/wes-8-465-2023), the wake deficit from OLAF, obtained from the Grid output, are consistent with what you would indeed expect. 

The issue is diverging from the original question, so I'll close this issue, but feel free to post a dedicated issue if the problem persists.

**Closed by ebranlard** 2023-08-24 17:25 UTC
Labels: Type: Question, Module: AeroDyn, Module: OLAF
