### ISSUE TITLE
Visual Studio Regression Test

### ISSUE THREAD

**Issue by bvumba** [OpenFAST/openfast#260] opened 2019-03-15 00:20 UTC
**Visual Studio Regression Test**

A clear and concise description of the bug.

Dear All, 

I have compiled OpenFast following the instructions in the manual ( https://openfast.readthedocs.io/en/master/source/install/index.html)  

I am attempting to do a regression test; however, I get the following error:

![bb](https://user-images.githubusercontent.com/48573266/54399835-6e7c3180-467d-11e9-8591-76dbeaaa487f.png)

 It is telling me that there is a syntax error in manualRegressionTest.py.

Any suggestions on how to solve this problem?

Many Thanks 
Ben

**Comment by rafmudaf** [comment] 2019-03-15 00:24
Hi @bvumba 

That script is written for python3, so switching your python executable should solve this problem. Please let me know how that works for you.

Thanks
Rafael

**Comment by bvumba** [comment] 2019-03-15 18:45
Hi Rafael,

Thank you for your prompt response. That solved the problem and I was able to run the regression test. Unfortunately, the results of the test show that a number of items have failed.

![OpenFast](https://user-images.githubusercontent.com/48573266/54454872-b354a680-4717-11e9-99f3-686bc06ff46a.png)

Do you have any suggestions on why this is the case?

Thanks Ben

**Comment by rafmudaf** [comment] 2019-03-15 19:16
These tests could have failed for a variety of reasons as they are very sensitive to your environment. For example, using a different version of the intel compiler or mkl library than the one used to generate the baseline is a common cause. My suggestion is to plot the results and visually inspect the failing cases.

Since you've already run the cases, you can just generate the plots with this command:
```
python3 manualRegressionTest.py ..\build\openfast_x64_Double.exe Windows Intel 1e-5 -n -p
```

The `-n` means don't run the case and `-p` means generate the plots. By the way, you need matplotlib installed for this to work. After it finishes successfully, you'll have a html file in `openfast\build\reg_tests` which you can open in any browser and navigate through the failed test cases.

**Comment by rafmudaf** [comment] 2019-03-15 19:17
I'm closing this issue, but we can continue the discussion here. Feel free to reopen the issue if needed.

**Comment by bvumba** [comment] 2019-03-20 21:52
Hi, 

Sorry to reopen this. However, despite trying numerous things I have not been able to make much progress. When I try to generate plots using the command you provided above it simply fails and no plots are generated. I have tried starting from scratch, including recompiling with a different Intel compiler and I end up in the same situation. Any help would be much appreciated.
![FAST](https://user-images.githubusercontent.com/48573266/54721651-c6081a80-4b1f-11e9-8009-b33e1a3ce7d8.png)

**Comment by rafmudaf** [comment] 2019-03-20 22:10
Can you verify that you're using python3 and you have matplotlib properly installed?

**Comment by bvumba** [comment] 2019-03-20 23:58
Hi,
I'm running python 3.7

![Python](https://user-images.githubusercontent.com/48573266/54726410-45054f00-4b30-11e9-90dc-5993042467b4.png)

Matplotlib should be installed

![pic](https://user-images.githubusercontent.com/48573266/54726673-5ef36180-4b31-11e9-9d4a-efe94d390b15.png)

**Comment by rafmudaf** [comment] 2019-03-26 16:13
Hmm I don't have a good guess at the problem yet, @bvumba. The `manualRegressionTest.py` script has a verbose option, `-v`, which will tell you the system command its running:
```
>>eagle@~/Development/openfast_intel/reg_tests (dev)$ python3 manualRegressionTest.py ../build/glue-codes/openfast/openfast linux intel 1e-5 -case WP_VSP_ECD -v
executing WP_VSP_ECD -- Using gold standard files with machine-compiler type linux-intel
../build/glue-codes/openfast/openfast ../build/reg_tests/glue-codes/openfast/WP_VSP_ECD/WP_VSP_ECD.fst > ../build/reg_tests/glue-codes/openfast/WP_VSP_ECD/WP_VSP_ECD.log
```

Using that information, you can either inspect the log file where the output is piped to (thats the argument in the command above after the `>`) or run the command manually in your cmd prompt and see what error you get.

**Comment by bvumba** [comment] 2019-03-28 22:16
Thanks, 

After starting from scratch and using an older version of Visual Studio (2015) I have managed to generate the plots.  11 of the tests still fail as can be seen in the image below. However, after inspecting the plots for the failed cases they are a little off but still pretty close. 

![Regression Test V2](https://user-images.githubusercontent.com/48573266/55196366-6687bb80-516c-11e9-910b-1afb103ab4a1.png)

**Comment by rafmudaf** [comment] 2019-03-28 22:26
Good, I'm glad to hear that you were able to generate the plots!

**Closed by rafmudaf** 2019-03-28 22:26 UTC
Labels: Type: Testing

**Comment by jsurabhi501** [comment] 2020-08-18 10:52
Hello,

I am running a regression test on Windows with Visual Studio, however, the test has failed.
![image](https://user-images.githubusercontent.com/68113824/90504523-82b93d80-e151-11ea-95e5-05f89dfc3d9b.png)

Any suggestions to solve this?
