### ISSUE TITLE
Bug report - Spurious Spike when Plotting Nodal Loads in ElastoDyn.

### ISSUE THREAD

**Issue by JarredK21** [OpenFAST/openfast#1204] opened 2022-07-29 23:34 UTC
**Spurious Spike when Plotting Nodal Loads in ElastoDyn.**
<A clear and concise description of the bug.>

**To Reproduce**
<Update the following list with your specific information.>
1. Compile OpenFAST 3.1.0 or any previous version with gcc. However, I have used V3.0.0 and older versions and seen the same result
2. Run NREL 5MW reference turbine case (included in Zip folder) with ElastoDyn DOF all FALSE, uniform inflow, no WakeMod, Steady AFAeroMod, remove tower effects (all settings are set up in the Zip folder). However I have tried with other reference turbines and seen the same result as with the 5MW.
3. Plot average ElastoDyn Blade moment or force (Eg:MLx) as a function of span
4. Average ElastoDyn blade moment or force shows a spurious spike at approx. 0.7r/R

**Expected behavior**
<A clear and concise description of what you expected to happen.>
Expect the load profile along the blade to follow the overall trend. Spurious spike completely deviates from overall trend.

**Screenshots, if applicable**
<Add screenshots to help explain your problem.>
Plot shows spurious spike in ElastoDyn nodal Load output MLx at approx. 0.7r/R span location.
![MLx_span](https://user-images.githubusercontent.com/100881721/181860040-f8730cef-5b0c-4c3e-8759-7c41c009176a.png)

**OpenFAST Version**
<Please provide as much detail as possible including git commit. The best information is a screenshot of the OpenFAST system description that prints when running OpenFAST:>
OpenFAST Version 3.1.0 - test_case OpenFAST files have been included in Zip File.

[test_case.zip](https://github.com/OpenFAST/openfast/files/9223913/test_case.zip)

```
******************************************************************************
********************
 OpenFAST

 Copyright (C)  National Renewable Energy Laboratory
 Copyright (C)  Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v2.0.0
 Compile Info:
  - Architecture: 64 bit
  - Precision: double
  - Date: Nov 27 2018
  - Time: 17:19:38
 Execution Info:
  - Date: 11/29/2018
  - Time: 10:52:28-0700
```

**System Information (please complete the following information):**
 - OS: <e.g. Ubuntu 14.04 or macOS 10.12>
 - Compiler: <e.g. GFortran 4.4>
 - Compiler settings: <e.g. CMake flags or other settings>

**Additional context**
<Add any other context about the problem here.>

**Comment by jjonkman** [comment] 2022-07-29 23:52
Dear @JarredK21,

I see that you are outputting many other radially distributed outputs from ElastoDyn and AeroDyn; do you notice any issues with these?  Please share the other radially distributed plots if you have them.

You mention gcc.  Are you suspecting the problem is isolated to gcc or is that the only version you've tried?

Thanks,

**Comment by JarredK21** [comment] 2022-07-30 00:10
Dear @jjonkman 

I don't have access to the other plots. But I can tell you all the Elastodyn averaged loads FLx, Fly, Flz, Mlx, Mly, Mlz as a function of span had the same spurious spike at the exact same location. Aerodyn results did not have this issue. 

No I don't believe this was a compiling issue, as I compiled OpenFAST v3.1.0 on NREL's EAGLE and had the same results.

Thanks,

Jarred

**Comment by ebranlard** [comment] 2022-07-30 21:10
Hi Jarred, 

I tried your input files with the official windows release versions 3.1 and 3.2 and couldn't reproduce your results (see figure below). 

It could be a platform or compiler issue. To rule out a postprocessing issue, you can try the following:

- adapt this [postprocessing script](https://github.com/OpenFAST/python-toolbox/blob/main/pyFAST/input_output/examples/Example_RadialPostPro.py) (using your mainFST and output file), and plot the quantity `dfRad_ED['B1MLx_[kN-m]']` 

- try to open your outfile in [pyDatView](https://github.com/ebranlard/pyDatView), then use the menu data > FAST radial average. 
   
![image](https://user-images.githubusercontent.com/1318316/181996090-5cdab18e-e925-4ba4-918b-62dd7f279000.png)

Let me know if you still see this weird spike. Feel free to send me your output file internally as well. 

Emmanuel

**Comment by ebranlard** [comment] 2022-07-30 21:34
There is definitely an issue with AeroDyn which is revealed occasionally by using different compilers and platforms. If I recall correctly it's related to the high-thrust correction but I never got the time to dive into it. You might be hitting this issue here. 

If you have time can you compile the aerodyn driver (`make aerodyn_driver`) the same way you compiled openfast (the executable ends up in `build/modules/aerodyn`, run the test case attached, and see how the AB1N002AxInd signal looks like (see the differences enclosed). 

Thanks a lot!

[AD_Sine_Bug.zip](https://github.com/OpenFAST/openfast/files/9227597/AD_Sine_Bug.zip)

![image](https://user-images.githubusercontent.com/1318316/181996826-c52ba250-e9df-4602-bafe-15bc9531ae05.png)

**Comment by JarredK21** [comment] 2022-08-01 20:41
Hi @ebranlard @jjonkman 

I ran the post processing code you recommended and that removed the spike. I don't know why. The code I wrote was simple enough. I extracted the channels using data = FASTOutputFile('NREL_5MW_Main.out').toDataFrame() then averaged over the time series and plotted as a function of span.

![MLx_span_mod](https://user-images.githubusercontent.com/100881721/182242512-f4aa8029-857e-4902-a77c-8a7c14537466.png)

And when I ran the aerodyn module with the zipped files the result matched the Windows result.

![AB1N002AxInd](https://user-images.githubusercontent.com/100881721/182242635-0a44fe39-1aa2-4a25-96a3-7aca53265315.png)

**Comment by ebranlard** [comment] 2022-08-01 22:10
@JarredK21 Thank you for trying these postprocessing scripts and trying this test case. 

It turns out the test case I sent reveals a single vs double precision issue, I'll post about it in another issue. 

I guess we can close this issue if that's alright with you.

**Comment by JarredK21** [comment] 2022-10-11 07:36
Hi,

Yes this issue can be closed.

Cheers,

Jarred
________________________________

**Closed** 2022-10-11 12:18 UTC
Labels: Type: Bug
