### ISSUE TITLE
HydroDyn Unexpected behaviour of Axial Inertia Force Calculation

### ISSUE THREAD

**Issue by cambrown52** [OpenFAST/openfast#555] opened 2020-10-05 14:24 UTC
### **Bug description**
Calculated axial inertia loads do not match expected behaviour when using strip theory members.

A dummy test case with regular linear waves applied to a single fixed and rigid member. Axial force coefficients AxCa and AxCp applied to both ends of the member. All other hydrodynamic force coefficients set to 0.

 - The axial force from Ca and Cp seem to refer to different reference masses
 - The length of the member seems to influence the loads

### **To Reproduce**
1. Define a template file with regular waves (H=3m T=8s) and a single member aligned with x axis at z=-15m. water depth 100m (see geometry figure below).
2. Define test cases with various choices member length and AxCa and AxCp
3. Using pre-compiled HydroDyn (v2.05.00) exe, run with HD driver file with fixed body (0 MorisonInputsMod)
4. Compare amplitudes of  "HydroFxi"

Input files attached for easier replication of result:
[OpenFastAxialHydrodynamicsBenchmarkStudy.zip](https://github.com/OpenFAST/openfast/files/5327941/OpenFastAxialHydrodynamicsBenchmarkStudy.zip)

![image](https://user-images.githubusercontent.com/69543151/95087781-69307d00-0722-11eb-96e7-2d2b79661586.png)

### **Expected behavior**
I expect the axial hydrodynamic force is calculated as follows:
`Fx=Cm_ax*reference_mass*water_particle_acceleration`
where,
`Cm_ax=Ca_ax+Cp_ax`
`reference_mass=rho*2/3*pi*R^3` (half sphere of water per end)

The discussion in https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=1740&p=8279&hilit=MemberAxCa1#p8279 seems to suggest the above definition is what is used in HydroDyn.

![image](https://user-images.githubusercontent.com/69543151/95090352-74d17300-0725-11eb-97c5-261a4b3b6db2.png)

### Unexpected Result summary
 **Question 1:**
Why does the Ca and Cp not equally contribute to the axial force?
![CaCpStudy](https://user-images.githubusercontent.com/69543151/95090716-e14c7200-0725-11eb-9474-1178681d48ba.png)

**Question 2:**
Why does the length of the member influence the axial force?
![LengthStudy](https://user-images.githubusercontent.com/69543151/95091231-7e0f0f80-0726-11eb-8cb0-2d80e455382b.png)

### **HydroDyn Version**
Pre-compiled version of HydroDyn (v2.05.00) was downloaded from the following link:
https://drive.google.com/file/d/1dw-dkdxDizU_v3lZtnsR7m0mD1dBVVhG/view?usp=sharing

```
This summary file was generated by HydroDyn v2.05.00 on 05-Oct-2020 at 14:26:53.
```

### **System Information (please complete the following information):**
 - OS: Windows 10
 - Compiler: n/a (pre-compiled executable used)
 - Compiler settings: n/a

**Comment by jjonkman** [comment] 2020-10-05 14:56
I'm closing this issue because it appears to be a duplicate of #554.

**Closed by jjonkman** 2020-10-05 14:56 UTC
Labels: Type: Bug
