### ISSUE TITLE
Problems to run unit_tests (Cygwin)

### ISSUE THREAD

**Issue by bmazetto** [OpenFAST/openfast#193] opened 2018-10-18 04:28 UTC
I am building OpenFAST on Windows with CMake and Cygwin 64-bit, according to the instructions on “readthedocs” page. However, when I try to run “make beamdyn_test”, I face some messages, like:

$ make beamdyn_utest
[  0%] Performing configure step for 'pfunit'
** WARNING: Install path not found! Please set PFUNIT or use -DINSTALL_PATH=...
++ Remember to set the environment variable PFUNIT to the install directory!
++ Example: export PFUNIT=OFF
-- Installing to INSTALL_PATH: OFF
(null): can't open file '/home/Bruno/code/OpenFAST/unit_tests/pfunit/source/GenerateAssertsOnArrays.py': [Errno 2] No such file or directory
(null): can't open file '/home/Bruno/code/OpenFAST/unit_tests/pfunit/source/GeneratedSources.py': [Errno 2] No such file or directory
Including generated files ''.
CMake Error at source/CMakeLists.txt:26 (include):
  include could not find load file:
    /home/Bruno/code/OpenFAST/unit_tests/pfunit-build/source/
-- Configuring incomplete, errors occurred!

Could someone help me solve this problem?

**Comment by dwalia** [comment] 2018-10-18 13:36
I am pretty new in compiling OpenFAST (just learning how to do that actually, using Linux). However, 

> (null): can't open file '/home/Bruno/code/OpenFAST/unit_tests/pfunit/source/GenerateAssertsOnArrays.py': [Errno 2] No such file or directory
(null): can't open file '/home/Bruno/code/OpenFAST/unit_tests/pfunit/source/GeneratedSources.py': 

Sounds like wrong path defintions to me. Furthermore, the paths do not sound like a typical windows-path because "/home/..." sounds like Linux paths. Are you sure that you have set up the paths to the respective directories correct? I am not familiar with CMake and Cygwin under Windows, so my assumptions above could also be wrong.

**Comment by bmazetto** [comment] 2018-10-20 13:32
Thanks for your response, dwalia. I gave up using Cygwin and tried a different approach, using Ubuntu on Windows 10. I followed the tutorial for building OpenFAST with Cmake on Linux and, even though I had some problems to install LAPACK and BLAS, I managed to properly run the beamdyn_utest.

**Comment by rafmudaf** [comment] 2018-10-29 21:49
@bmazetto 

I believe this is related to CMake not finding an appropriate python interpreter when it configures the unit test package specifically. On which version of openfast did you run into this? I recently made some updates which may fix this to the `dev` branch, and they were even more recently merged into `master`. If you haven't yet, pull the latest from `master`, rerun cmake, and try again.

Thanks
Rafael

**Comment by rafmudaf** [comment] 2018-11-07 18:50
@bmazetto I'm closing this issue since its gone silent but feel free to reopen as needed.

**Comment by bmazetto** [comment] 2019-07-31 02:48
Hello guys, I'm trying to install OpenFAST using Cygwin again. The previous installation using Ubuntu on Windows 10 did not work very well. Now, I'm facing some problems with unit tests. When I try to "make beamdyn_utest", I receive some messages during the process:

_____________________________________________________________________________________________________
/home/Bruno/code/OpenFAST/modules-local/nwtc-library/src/ModMesh.f90:3477:0:

                      ErrMsg = 'MeshExtrapInterp2:'//TRIM(ErrMsg)

Warning: ‘__builtin_memset’: specified size 18446744073709551598 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
/home/Bruno/code/OpenFAST/modules-local/nwtc-library/src/ModMesh.f90:3484:0:

                      ErrMsg = 'MeshExtrapInterp2:'//TRIM(ErrMsg)

Warning: ‘__builtin_memset’: specified size 18446744073709551598 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
/home/Bruno/code/OpenFAST/modules-local/nwtc-library/src/ModMesh.f90:3491:0:

                      ErrMsg = 'MeshExtrapInterp2:'//TRIM(ErrMsg)

Warning: ‘__builtin_memset’: specified size 18446744073709551598 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
/home/Bruno/code/OpenFAST/modules-local/nwtc-library/src/ModMesh.f90:3316:0:

                      ErrMsg = 'MeshExtrapInterp1:'//TRIM(ErrMsg)

Warning: ‘__builtin_memset’: specified size 18446744073709551598 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
/home/Bruno/code/OpenFAST/modules-local/nwtc-library/src/ModMesh.f90:3323:0:

                      ErrMsg = 'MeshExtrapInterp1:'//TRIM(ErrMsg)

Warning: ‘__builtin_memset’: specified size 18446744073709551598 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
__________________________________________________________________________________________________________

And by the end, I get:
_________________________________________________________________________________________________________
Scanning dependencies of target beamdyn_utest
[ 78%] Building Fortran object unit_tests/CMakeFiles/beamdyn_utest.dir/tests/test_tools.F90.o
[ 78%] Building Fortran object unit_tests/CMakeFiles/beamdyn_utest.dir/tests/test_BD_CheckRotMat.F90.o
[ 78%] Building Fortran object unit_tests/CMakeFiles/beamdyn_utest.dir/tests/test_BD_CrvCompose.F90.o
[ 82%] Building Fortran object unit_tests/CMakeFiles/beamdyn_utest.dir/tests/test_BD_CrvExtractCrv.F90.o
[ 82%] Building Fortran object unit_tests/CMakeFiles/beamdyn_utest.dir/tests/test_BD_CrvMatrixH.F90.o
[ 82%] Building Fortran object unit_tests/CMakeFiles/beamdyn_utest.dir/tests/test_BD_CrvMatrixR.F90.o
[ 82%] Building Fortran object unit_tests/CMakeFiles/beamdyn_utest.dir/tests/test_BD_DistrLoadCopy.F90.o
[ 86%] Building Fortran object unit_tests/CMakeFiles/beamdyn_utest.dir/tests/test_BD_GaussPointWeight.F90.o
[ 86%] Building Fortran object unit_tests/CMakeFiles/beamdyn_utest.dir/tests/test_BD_GenerateGLL.F90.o
[ 91%] Building Fortran object unit_tests/CMakeFiles/beamdyn_utest.dir/tests/test_BD_GravityForce.F90.o
[ 91%] Building Fortran object unit_tests/CMakeFiles/beamdyn_utest.dir/tests/test_BD_InitShpDerJaco.F90.o
[ 91%] Building Fortran object unit_tests/CMakeFiles/beamdyn_utest.dir/tests/test_BD_InputGlobalLocal.F90.o
[ 91%] Building Fortran object unit_tests/CMakeFiles/beamdyn_utest.dir/tests/test_BD_QPData_mEta_rho.F90.o
[ 91%] Building Fortran object unit_tests/CMakeFiles/beamdyn_utest.dir/tests/test_BD_diffmtc.F90.o
[ 95%] Building Fortran object unit_tests/CMakeFiles/beamdyn_utest.dir/tests/test_ExtractRelativeRotation.F90.o
[100%] Building Fortran object unit_tests/CMakeFiles/beamdyn_utest.dir/pfunit/include/driver.F90.o
make[3]: *** No rule to make target 'unit_tests/pfunit/lib/pfunit.lib', needed by 'unit_tests/beamdyn_utest.exe'.  Pare.
make[2]: *** [CMakeFiles/Makefile2:3166: unit_tests/CMakeFiles/beamdyn_utest.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3178: unit_tests/CMakeFiles/beamdyn_utest.dir/rule] Error 2
make: *** [Makefile:1059: beamdyn_utest] Error 2
_________________________________________________________________________________________________________

I don't know how to solve these errors or what is causing it. Has someone experienced the same situation? What should I do to solve this?

**Comment by dwalia** [comment] 2019-07-31 06:49
Dear bmazetto. When I built OpenFAST 2.0 on Arch, I ran into the same problems. Therefore, I decided to skip the unit regression tests. OpenFAST was the first PKGBUILD I wrote. So I was heavily supported by the community in the Arch forums. On page 3 in the respective topic, the complexity of testing OpenFAST was discussed. Probably that doesn´t help you, and hopefully rafmudaf has more useful hints. In any case the link to the thread in the Arch forums: https://bbs.archlinux.org/viewtopic.php?id=241145&p=3

**Comment by rafmudaf** [comment] 2019-07-31 16:38
@bmazetto can you give more details about this line: ``` The previous installation using Ubuntu on Windows 10 did not work very well.```

**Comment by rafmudaf** [comment] 2019-07-31 17:28
@bmazetto as for the build problems for the `beamdyn_utest` target on Cygwin, your current cmake configuration is setup incorrectly as its looking for `pfunit.lib` but it should be looking for `libpfunit.a`. Fortunately, this is already corrected in the `dev` branch through pull request https://github.com/OpenFAST/openfast/pull/271. So check out the dev branch and try again:
```
cd <path to openfast>
git checkout dev
git pull origin dev

# you might want to remove your build directory just to be safe, but I'll let you decide
# rm -rf build && mkdir build

cd build
cmake .. -DBUILD_TESTING=ON
make beamdyn_utest
```

And please post the results of this so we can verify whether this bug is fixed. Thanks for your support of OpenFAST!

**Comment by bmazetto** [comment] 2019-08-02 01:20
@rafmudaf , I had had some problems with the Regression Tests  (#197) when using Ubuntu on Windows 10. Since I had to run some simulations as soon as possible back then, I've decided to use FAST v8 instead of OpenFAST.

**Comment by bmazetto** [comment] 2019-08-02 02:18
@dwalia and @rafmudaf , thank you both for your comments. @rafmudaf , now it's working! 

![image](https://user-images.githubusercontent.com/44245549/62339502-9a744400-b4b2-11e9-8f5f-2273f583ff52.png)

**Comment by rafmudaf** [comment] 2019-08-02 02:40
Excellent! Thanks for the update.

**Comment by PeterV310** [comment] 2019-10-01 03:48
Maybe someone can help me .. Been a week trying to install and have OpenFAST running .. :( .. have arrived to the below point ..

Any hints please?

Owner@DESKTOP-U7FJRBS ~/OpenFAST/OPenFAST/build
$ make beamdyn_utest
[  0%] Performing configure step for 'pfunit'
-- Installing to INSTALL_PATH: ON
C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\python.exe: can't open file '/home/Owner/OpenFAST/OPenFAST/unit_tests/pfunit/source/GenerateAssertsOnArrays.py': [Errno 2] No such file or directory
C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\python.exe: can't open file '/home/Owner/OpenFAST/OPenFAST/unit_tests/pfunit/source/GeneratedSources.py': [Errno 2] No such file or directory
Including generated files ''.
CMake Error at source/CMakeLists.txt:26 (include):
  include could not find load file:

    /home/Owner/OpenFAST/OPenFAST/build/unit_tests/pfunit-build/source/


-- Configuring incomplete, errors occurred!
See also "/home/Owner/OpenFAST/OPenFAST/build/unit_tests/pfunit-build/CMakeFiles/CMakeOutput.log".
make[3]: *** [unit_tests/CMakeFiles/pfunit.dir/build.make:107: unit_tests/pfunit-stamp/pfunit-configure] Error 1
make[2]: *** [CMakeFiles/Makefile2:3307: unit_tests/CMakeFiles/pfunit.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3282: unit_tests/CMakeFiles/beamdyn_utest.dir/rule] Error 2
make: *** [Makefile:1085: beamdyn_utest] Error 2

**Comment by jonmtz** [comment] 2019-11-11 15:31
Dear all,

Until now I used FAST v8 and now I am moving to OpenFAST. I already cloned the latest master branch and installed OpenFAST using CMake and Cygwin in Windows 10. The OpenFAST version i got is OpenFAST-v2.1.0-dirty, and now I am trying to perform the unit tests.

I ran the command `$ cmake .. -DBUILD_TESTING=ON` on build directory, and after that I tried to perform the beamdyn unit test, as described in [https://openfast.readthedocs.io/en/master/source/testing/unit_test.html](url) with the command `$ make beadyn_utest`

Nevertheless, I got the following error.

```
myname@myname /cygdrive/d/Users/myname/Documents/OpenFAST/build
$ make beamdyn_utest
Scanning dependencies of target pfunit
[  0%] Creating directories for 'pfunit'
[  4%] No download step for 'pfunit'
[  4%] No patch step for 'pfunit'
[  4%] No update step for 'pfunit'
[  8%] Performing configure step for 'pfunit'
-- The Fortran compiler identification is GNU 7.4.0
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/f95 supports Fortran 90
-- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
** WARNING: Install path not found! Please set PFUNIT or use -DINSTALL_PATH=...
++ Remember to set the environment variable PFUNIT to the install directory!
++ Example: export PFUNIT=OFF
-- Installing to INSTALL_PATH: OFF
CMake Error at /usr/share/cmake-3.14.5/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.14.5/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.14.5/Modules/FindPythonInterp.cmake:160 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  source/CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!
See also "/cygdrive/d/Users/myname/Documents/OpenFAST/build/unit_tests/pfunit-build/CMakeFiles/CMakeOutput.log".
make[3]: *** [unit_tests/CMakeFiles/pfunit.dir/build.make:107: unit_tests/pfunit-stamp/pfunit-configure] Error 1
make[2]: *** [CMakeFiles/Makefile2:3203: unit_tests/CMakeFiles/pfunit.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3178: unit_tests/CMakeFiles/beamdyn_utest.dir/rule] Error 2
make: *** [Makefile:1059: beamdyn_utest] Error 2
```

As I understand, the problem is that the python interpreter is not found, but I do not know how to proceed to solve the problem.

Thank you in advance for the help!

Jon

**Comment by rafmudaf** [comment] 2019-11-11 16:19
@jonmtz Could you switch to the `dev` branch and try again? There are some changes in the `dev` branch for compiling and running the unit tests. It may not fix your specific issue, but at least we'll be on the latest code.

To switch branches, move into your OpenFAST directory and do this:
```
git fetch
git checkout -b dev origin/dev
```

**Comment by jonmtz** [comment] 2019-11-12 08:10
Dear @rafmudaf ,

Thank you for your fast reply. I checked out in the develop branch (I am using SmartGit, since your command did not work for me, don't know why), did the `$ cmake .. -DBUILD_TESTING=ON` again, but the error seems to be the same when trying to run the test. I attach the specific error obtained:

```
myname@myname /cygdrive/d/Users/myname/Documents/OpenFAST/build
$ make beamdyn_utest
[  0%] Performing configure step for 'pfunit'
** WARNING: Install path not found! Please set PFUNIT or use -DINSTALL_PATH=...
++ Remember to set the environment variable PFUNIT to the install directory!
++ Example: export PFUNIT=OFF
-- Installing to INSTALL_PATH: OFF
CMake Error at /usr/share/cmake-3.14.5/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.14.5/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.14.5/Modules/FindPythonInterp.cmake:160 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  source/CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!
See also "/cygdrive/d/Users/myname/Documents/OpenFAST/build/unit_tests/pfunit-build/CMakeFiles/CMakeOutput.log".
make[3]: *** [unit_tests/CMakeFiles/pfunit.dir/build.make:107: unit_tests/pfunit-stamp/pfunit-configure] Error 1
make[2]: *** [CMakeFiles/Makefile2:3232: unit_tests/CMakeFiles/pfunit.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3207: unit_tests/CMakeFiles/beamdyn_utest.dir/rule] Error 2
make: *** [Makefile:1072: beamdyn_utest] Error 2
```
Besides, I tried to run all the tests to check if any of them works with `$ ctest`, but all of them failed. 

````
0% tests passed, 37 tests failed out of 37

Label Time Summary:
aerodyn14    =   2.12 sec*proc (7 tests)
aerodyn15    =   5.48 sec*proc (19 tests)
beamdyn      =   3.29 sec*proc (11 tests)
dynamic      =   0.88 sec*proc (3 tests)
elastodyn    =   7.30 sec*proc (25 tests)
hydrodyn     =   2.00 sec*proc (7 tests)
linear       =   1.26 sec*proc (4 tests)
map          =   0.86 sec*proc (3 tests)
moordyn      =   0.28 sec*proc (1 test)
openfast     =   8.57 sec*proc (29 tests)
servodyn     =   7.62 sec*proc (26 tests)
static       =   1.13 sec*proc (4 tests)
subdyn       =   0.86 sec*proc (3 tests)

Total Test time (real) =  11.04 sec
````
In case it is useful, the software I installed for doing this were Cygwin 64-bit, CMake 3.16.0 and Python 3.8.0

Thank you for your help,

Jon

**Comment by rafmudaf** [comment] 2019-11-12 14:38
@jonmtz In `openfast/unit_tests/CMakeLists.txt`, change the following block at line 34. I think this will pass along your Python interpreter path from the OpenFAST CMake project to the pFUnit CMake project.

```
### pfunit
include(ExternalProject)
set(ExternalProjectCMakeArgs
  -DCMAKE_INSTALL_PREFIX=${PROJECT_BINARY_DIR}/pfunit
  -DROBUST=OFF
  -DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE}.   # <---- ADD THIS LINE
)
```

Let me know how this works.

**Comment by rafmudaf** [comment] 2019-11-12 15:02
Is that the Windows Python and can you use that Python interpreter in Cygwin? You can test that by opening a new Cygwin terminal and enter:
```
/cygdrive/c/Windows/py.exe
```
If that opens a Python prompt and you can run simple commands (something like `print("hello")`) then you're fine.

Running from the `build` directory is what you're supposed to do, so thats fine, also.

Otherwise, I'm not sure what might be the problem. You could try to old unplug-it trick by deleting your entire `build` directory and starting over since you've now changed quite a bit from when you started.

**Comment by jonmtz** [comment] 2019-11-13 08:35
Dear @rafmudaf ,

You were right, I had installed Windows Python and cygwin has its own python to install, so I did it. Besides, as you said, I removed all the build folder and performed the commands: `FC=gfortran cmake ../` and `make` in order to create it again. A fact to comment is that, in this case, in order to create the build files, I used the Cygwin.bat command window instead of using Cygwin64 Terminal, and the execution was considerably faster.

Nevertheless, when trying to perform again the `beamdyn_utest` I keep having pretty the same error:

```
myname@myname /cygdrive/d/Users/myname/Documents/OpenFAST/build
$ make beamdyn_utest
Scanning dependencies of target pfunit
[  4%] Creating directories for 'pfunit'
[  4%] No download step for 'pfunit'
[  8%] No patch step for 'pfunit'
[  8%] No update step for 'pfunit'
[  8%] Performing configure step for 'pfunit'
-- The Fortran compiler identification is GNU 7.4.0
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/f95 supports Fortran 90
-- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
** WARNING: Install path not found! Please set PFUNIT or use -DINSTALL_PATH=...
++ Remember to set the environment variable PFUNIT to the install directory!
++ Example: export PFUNIT=OFF
-- Installing to INSTALL_PATH: OFF
-- Found PythonInterp: /usr/bin/python3.
Including generated files ''.
CMake Error at source/CMakeLists.txt:26 (include):
  include could not find load file:

    /cygdrive/d/Users/myname/Documents/OpenFAST/build/unit_tests/pfunit-build/source/


-- Configuring incomplete, errors occurred!
See also "/cygdrive/d/Users/myname/Documents/OpenFAST/build/unit_tests/pfunit-build/CMakeFiles/CMakeOutput.log".
make[3]: *** [unit_tests/CMakeFiles/pfunit.dir/build.make:107: unit_tests/pfunit-stamp/pfunit-configure] Error 1
make[2]: *** [CMakeFiles/Makefile2:3232: unit_tests/CMakeFiles/pfunit.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3207: unit_tests/CMakeFiles/beamdyn_utest.dir/rule] Error 2
make: *** [Makefile:1072: beamdyn_utest] Error 2
```
Any ideas?

Thank you,

Jon

**Comment by rafmudaf** [comment] 2019-12-18 02:18
@jonmtz are you still facing this problem? If so, verify that the python interpreter you're using `/usr/bin/python3` can run in the `Cygwin.bat` prompt.

I'm closing the issue, but will reopen when you respond.

**Closed by rafmudaf** 2019-12-18 02:18 UTC
Labels: System: MinGW/CygWin, Type: Build issue, Type: Testing

**Comment by jonmtz** [comment] 2019-12-20 08:12
Dear @rafmudaf,

As I was not able to compile using cygwin, I decided to use the precompiled version of OpenFAST. Nevertheless, I will try what you say to be able to use the latest versions of OpenFAST. 

As for the precompiled binaries for Windows:
- OpenFAST v2.2.0 release still does not have the binaries attached.
- With OpenFAST v2.1.0, the executable for 32 bits (openfast_Win32.exe) does not work, or at least I was not able to do so.

Is it expected to upload v2.2.0. binaries soon?

Thank you for your help,

Jon

**Comment by rafmudaf** [comment] 2019-12-20 22:52
Hey @jonmtz I've uploaded the v2.2.0 binaries on the release page
