### ISSUE TITLE
Yaw angle displaces turbine. 

### ISSUE THREAD

**Issue by lusoalman** [OpenFAST/openfast#1683] opened 2023-07-12 15:00 UTC
Dear community, 

I am running a model with FASTFarm v3.5.0. on Windows 10. I want to visualize the transversal (y and z) flow in the wake of a wind turbine model (D=1.2m). It is a very simple model because all DOF are deactivated. Everything is working fine but when I change the yaw to something other than 0 my yawed turbine ends up in a different y-position (see picture). The y-position gets more off the higher the yaw and also changes direction with a negative yaw angle.
5deg NacYaw:
![image](https://github.com/OpenFAST/openfast/assets/135970332/7cdb7e0c-8abe-442f-b0ff-8fb2cb1b6ded)
10deg NacYaw:
![image](https://github.com/OpenFAST/openfast/assets/135970332/0f2b99ef-ca30-4c01-b733-31ad431e640a)
0 deg NacYaw:
![image](https://github.com/OpenFAST/openfast/assets/135970332/f7d40e7a-a42a-4812-a4bb-54809c5db0f1)

[WTM_D1d2_T1_6mps.txt](https://github.com/OpenFAST/openfast/files/12027880/WTM_D1d2_T1_6mps.txt) .fst
[WTM_D1d2_ElastoDyn_T1.txt](https://github.com/OpenFAST/openfast/files/12027881/WTM_D1d2_ElastoDyn_T1.txt) .dat
[WTM_D1d2_2T5D.txt](https://github.com/OpenFAST/openfast/files/12027882/WTM_D1d2_2T5D.txt) .fstf

I don't understand where this is coming from.  I don't use Servodyn at all.  

I would be very grateful for any help, I really don't know what else to do.

All the best, 
Sara

**Comment by jjonkman** [comment] 2023-07-15 17:04
Dear @lusoalman,

There have been several issues showing arising in FAST.Farm during the ongoing rework of the InflowWind module released in OpenFAST v3.5.  Hopefully these issues will be fixed with the release of upcoming release of OpenFAST v3.5.1.  Before then, can you rerun your model in FAST.Farm within OpenFAST v3.4 and verify the issue goes away?

Best regards,

**Comment by lusoalman** [comment] 2023-07-16 17:42
Dear @jjonkman,

Thanks a lot for the reply! Unfortunately running it with v3.4 did not change anything.
It looks like the y-coordinate is somehow linked to the yaw angle... is there another possible origin for the unwanted shift?

Thank you and best regards, 
Sara

**Comment by jjonkman** [comment] 2023-07-17 20:06
Dear @lusoalman,

OK, thanks for checking FAST.Farm within OpenFAST v3.4.

I believe I now understand what the problem is.  I see that you are using DEFAULT settings for the horizontal wake-deflection correction parameters in FAST.Farm.  The DEFAULT values of `C_HWkDfl_OY` and `C_HWkDfl_xY` were calibrated for the NREL 5-MW baseline wind turbine, but your wind turbine is **much** smaller (presumably a model-scale wind turbine).  My guess is that these DEFAULT values are not valid at model scale, specifically the DEFAULT value of `C_HWkDfl_OY` = 0.3 m/deg.  I would suggest disabling the horizontal wake-deflection correction (by setting `C_HWkDfl_O` = `C_HWkDfl_OY` = `C_HWkDfl_x` = `C_HWkDfl_xY` = 0) or recalibrate the values for your model.

Best regards,

**Comment by lusoalman** [comment] 2023-07-24 11:04
Dear @jjonkman,

I'm sorry for the late reply. 
This did the trick!! Thank you so much. I would not have found it myself.

All the best, 
Sara

**Closed** 2023-07-24 12:17 UTC
Labels: Type: Bug, FAST.Farm
